### ISSUE TITLE
Support categories for  notifications

### ISSUE THREAD

**Issue by tunjiaramide** [OneSignal/OneSignal-WordPress-Plugin#101]
How can we map our Wordpress categories to one signal segments,  so once we submit any post, and select the Editorial category, it should send to all the subscribers under the Editorial segment in one signal, and not everyone.

Please inform us if this feature is available yet, if not can you direct us on how to achieve this. We are trying to send notification based on the post category a user only wants.

Thank you

**Comment by jasonpang** [comment]
Hi @tunjiaramide,

This feature is only possible with engineering.

Please see [this documentation](https://documentation.onesignal.com/docs/wordpress#section-how-do-i-categorize-users-and-send-notifications-to-specific-categories-of-users-) that describes how to do half of this: tagging subscribers to be marked as being in the Editorial segment.

You may want to tag users who visit special pages X, Y, and Z to have the Editorial tag. So `OneSignal.sendTags({editorial: true});`

Then visit the OneSignal dashboard and create a _Segment_, where the users in this segment is defined by those who have the tag key "editorial" and tag value "true".

The other half, which is sending to users marked as being in the Editorial segment, is described here: 
  - Read the intro and orange box (https://documentation.onesignal.com/docs/wordpress#section-customizing-wordpress-plugin-behavior)
  - https://documentation.onesignal.com/docs/wordpress#section-onesignal_send_notification-filter
    - The only fields override you need is something like (untested):

```php
$fields['included_segments'] = array("My Editorial Segment Name");
```

**Comment by tunjiaramide** [comment]
@jasonpang 
Thanks for your reply, i was able to tag my individual page for example, this script only appears on posts pages under the Editorial Category

<script data-cfasync="false" type="text/javascript">
			OneSignal.sendTags({editorial: true});
		</script> 

And i have created the segment and notification filter, once i create an Editorial post it sends only to my Editorial segment, **but still when i create a post under Sports or Politics it still sends post notification to Editorial segment. Please how do i correct this.**

**Comment by jasonpang** [comment]
Hey @tunjiaramide,

Can you modify your onesignal_send_notification filter to only add the included_segments code if the post is an editorial post?

So something like:

```php
if (<IS EDITORIAL CATEGORY>) {
  /* If the post type is an editorial, only send to my editorial segment */
  $fields['included_segments'] = array("My Editorial Segment Name");
}
```

Note: You will have to double check how to get the category. I think it's like https://developer.wordpress.org/reference/functions/get_the_category/, and you just loop through until you find Editorial or not.

**Comment by tunjiaramide** [comment]
@jasonpang Thanks this should work i will give it a try and give you feedback.

**Comment by tunjiaramide** [comment]
@jasonpang thanks it worked.
