### ISSUE TITLE
Featured image from WordPress posts on iOS rich notifications

### ISSUE THREAD

**Issue by filipekids** [OneSignal/OneSignal-WordPress-Plugin#102]
Hi,

It will be nice if Push Notifications sent on new blog posts from WordPress contains the featured image on iOS notifications.

Images with a Image URL sent through OneSignal.com works fine, thumbnails preview appears on the device. But not from WordPress plugin.

**Comment by fatsjohonimahnn** [comment]
iOS devices doe not support web push notifications. As soon as Apple supports this, we will make sure this is doable.

**Comment by iDevo** [comment]
Hi @fatsjohonimahnn ! 
I've just setup your great work in Wordpress and currently the plugin is able trigger a notification for iOS via OneSignal, with plain text using "Send notifications additionally to iOS & Android platforms".

Just to understand is the right way. However, it is currently not possible, that the plugin hands on the the **content_available** flag and the **media** URL of the featured image of a post to OneSignal, like it's possible triggering a new push manually?

Thank yo very much!
Mark

<img width="689" alt="screen shot 2018-10-01 at 09 01 39" src="https://user-images.githubusercontent.com/8428287/46274211-ec79cf80-c558-11e8-9bde-4a9ae0aa9e36.png">
