### ISSUE TITLE
Posts types Filter

### ISSUE THREAD

**Issue by munaterai** [OneSignal/OneSignal-WordPress-Plugin#103]
Good morning, what a good job they have done, it has helped me a lot with the creation of my project.

I would like to ask for help, I have not been able to do a wordpress filter to only send notifications of this Custom Post Type "event".

i want everything else blocked. my other custom post types (job_listing, location, wpcf7_contact_form)

could you help me..

**Comment by jasonpang** [comment]
Hi @munaterai,

What code have you tried so far?

**Comment by munaterai** [comment]
hi, 
thanks for answering
already make the segments in one signal dashboard.

the code is..


add_filter('onesignal_send_notification', 'onesignal_send_notification_filter', 10, 4);
function onesignal_send_notification_filter($fields, $new_status, $old_status, $post)
		{

	$event_id1 = get_the_ID ( $post->ID );    <= the id of the post.

	
	$getlocation1 = $wpdb->get_results( "SELECT location_id FROM wp_em_events WHERE post_id = $event_id1 " );      <=  query => location id of the post
	$locationid1 = $getlocation1[0]->location_id;  <= the location id


	$getcity1 = $wpdb->get_results( "SELECT location_town FROM wp_em_locations WHERE location_id = $locationid1 " );  <= query => location name city
	$city1 = $getcity1[0]->location_town;    <= the location name

	$getregion1 = $wpdb->get_results( "SELECT location_state FROM wp_em_locations WHERE location_id = $locationid1 " );     <= query => location name state
	$getregion2 = $getregion1[0]->location_state;   <= the location state name

	$getcountry1 = $wpdb->get_results( "SELECT location_country FROM wp_em_locations WHERE location_id = $locationid1 " );      <= query =>  location name country
	$getcountry2 = $getcountry1[0]->location_country;     <= the location name country


	$promotiontype1 = $wpdb->get_results( "SELECT term_taxonomy_id FROM wp_term_relationships WHERE object_id = $event_id1 " );      <= query => promotion type id
	$promotiontype2 = $promotiontype1[0]->term_taxonomy_id;	  <= the promotion id
	
	
	if ( $promotiontype2 == "185" ) {
	$segmento1 = $city1;
	} elseif ( $promotiontype2 == "186" ){
	$segmento1 = $city1;
	} elseif ( $promotiontype2 == "187" ){
	$segmento1 = $city1;
	} elseif ( $promotiontype2 == "188" ){
	$segmento1 = $getregion2;
	} elseif ( $promotiontype2 == "190" ){
	$segmento1 = $getregion2;
	} elseif ( $promotiontype2 == "192" ){
	$segmento1 = $getregion2;
	} elseif ( $promotiontype2 == "189" ){
	$segmento1 = $getcountry2;
	} elseif ( $promotiontype2 == "191" ){
	$segmento1 = $getcountry2;
	} elseif ( $promotiontype2 == "193" ){
	$segmento1 = $getcountry2;
	}

		   // Change which segment the notification goes to
		  $fields['included_segments'] = array('$segmento1');
  
		  return $fields;
			}



This is my code ...  jejeje...  I'm not very good with the wordpress code.

supposedly, you should change the segment, but do not ... block the entire website. I do not know what to do.

Also, i speak spanish

**Comment by munaterai** [comment]
Hi.. i did the filtre.. 👍

But i have a question..

I have Users without location.. i Guess.. they use PC browser.. is a way to get the user location on browsers.. . ?  Wp plugins.. or script..

**Comment by jasonpang** [comment]
Hi @munaterai,

Glad you got it!

Accessing a reasonably accurate location requires browser geolocation permissions similar to the notification permissions required for web push. One alternative is to read the IP address from the request and get country-level accurate location.
