### ISSUE TITLE
how to send notification via php in wordpress

### ISSUE THREAD

**Issue by boudgeau** [OneSignal/OneSignal-WordPress-Plugin#104]
i want to integrate onesignal with wpallimport to sent notification while importing new posts, i'm able to some php function during the import process, what php command shall i use to send notification on each post?

**Comment by jasonpang** [comment]
Please see https://documentation.onesignal.com/docs/wordpress, https://documentation.onesignal.com/docs/wordpress#section-customizing-wordpress-plugin-behavior (orange box), and https://documentation.onesignal.com/docs/wordpress#section-onesignal_include_post-filter.
