### ISSUE TITLE
Open notifications in app - redirect to the url (Wordpress + Android)

### ISSUE THREAD

**Issue by Aminericher** [OneSignal/OneSignal-WordPress-Plugin#109]
Hallo,

First, thank you very much for such a great service & plugin.

I have developped an app using Android Studio, converting my WordPress website into an android app (webView), and with no prior coding knowledge, as I simply followed [the instructions in this video](https://www.youtube.com/watch?v=AnHWVbK323A), and copied the codes in [your documentation](https://documentation.onesignal.com/docs/android-sdk-setup) in the appropriate file.
The notifications are successfully delivered, however when I click on, it just open the app without any redirection to the url sent in the notification.

I implemented the codes in [the documentation page](https://documentation.onesignal.com/docs/web-push-wordpress-faq#section-sending-notifications-to-both-browsers-and-mobile-apps). But when I try to add the code in [the example you give in this link](https://stackoverflow.com/questions/37928758/how-do-i-use-onesignal-with-android-studio-to-allow-notifications-to-link-direct/37935082#37935082), no success, as I still get errors in my android app code as this image: https://ibb.co/mPV56S (I’m newbie in coding).

How to redirect to the exact url in the android app ?

Your help will be appreciated (exactly which code to add and in which file ?)

Thank you in advance

**Comment by jasonpang** [comment]
Hi @Aminericher,

Looks like you're starting out in the right direction! A notification sent to your app successfully opens your app, and now your remaining tasks are to read the additional data from the notification and open your app's webview to a specific URL.

This question is more related to Android webviews and opening specific URLs in an Android webview. What you're adding will require some coding, and you'll need to search the web for solutions to some of the issues. We recommend searching Google.com and StackOverflow.com for answers to some of the errors you're getting and other questions, as many other developers just starting out post questions on StackOverflow.com and get them answered. For example, "Cannot resolve method optString" probably means you're missing an import statement to JSONObject. We can't write your application's code for you.

It also looks like you're using an older version of our Android SDK, so we recommend using the newest version.
