### ISSUE TITLE
Deprecated Functions - PHP 7.2

### ISSUE THREAD

**Issue by studio404pl** [OneSignal/OneSignal-WordPress-Plugin#110]
with PHP 7.2 and WP_DEBUG enabled i am getting following errors:

`Deprecated: Function create_function() is deprecated in /plugins/onesignal-free-web-push-notifications/onesignal-widget.php on line 46`

`Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /plugins/onesignal-free-web-push-notifications/onesignal-settings.php on line 122`

**Comment by jasonpang** [comment]
Hi @studio404pl,

Thanks for letting us know! We'll most likely update the deprecated code in our next few releases.

**Comment by Glashkoff** [comment]
Several months passed. Development is stopped?

**Comment by gdeglin** [comment]
We're still working on things, but our focus has been elsewhere. Sorry we haven't been able to get to this issue for a while.

**Comment by davideprevosto** [comment]
Do you have any ETA about this issue?

**Comment by swannknani** [comment]
@gdeglin Do you know when #130 will be merged ?

**Comment by jkasten2** [comment]
This issue has been fixed version 1.16.8. Thanks.
