### ISSUE TITLE
Wordpress features

### ISSUE THREAD

**Issue by Jojonema** [OneSignal/OneSignal-WordPress-Plugin#111]
First of all. I love onesignal and the possibilities it provides. Thank you for this awesome service!

That said I think that the Wordpress plugin could be improved in some points. 
1. Delivery time options as on onesignal.com would be great. At the moment, notifications are sent the moment the post is published. Would be great if one could select to deliver them at the recommended time.
2. Category base subscription: It would be great if users could be subscribed to different segments depending on what category they are browsing. Also, if they would be notified only if a post fits the certain category that they subscribed to would be nice.
3. Featured image options: Set the featured image of the post as notification thumbnail would be nice.

**Comment by jasonpang** [comment]
Hi @Jojonema,

Thanks for your feedback!

Both feature requests delivery customization and category-based subscriptions are being tracked internally.

For setting the featured image of the post as a notification thumbnail, you should be able to find this on our WordPress plugin's configuration as "Use the post's featured image for the notification icon". There is a similar option below it for the large image (on supported environments) called "Use the post's featured image for Chrome's large notification image".
