### ISSUE TITLE
Translation/Multilingual

### ISSUE THREAD

**Issue by Dedi-Data** [OneSignal/OneSignal-WordPress-Plugin#112]
Hi,
Do you accept a pull request for making your plugin ready for translations?
I can help you to make it multilingual using wordpress translation system (translate.wordpress.org)

I am currently a WordPress General Translation Editor (GTE)

Waiting for your reply...
Regards

**Comment by jasonpang** [comment]
Hi @Dedi-Data,

We'd like to review [How to Internationalize Your Plugin](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin) a bit more first to see what kind of options we have, what the best practices are, and what's involved. So far, it looks mostly like a lot of string replacements to use `__("", "plugin-domain")` and some `sprintf()` for the strings with variables. But our plugin also supports up to 3.8, so [we have to add `load_plugin_textdomain()`](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain) and I wanted to look more into that. We'll try to take a look soon, thank you for your enthusiasm in wanting to contribute! We just want to make sure we know what we have to change once we accept the PR.

**Comment by Dedi-Data** [comment]
@jasonpang 
Hi,
Yes, You can convert text using __() or _e() or [others](https://codex.wordpress.org/L10n)
And you need just add your text domain in your plugin details
```
/*
 * Plugin Name: My Plugin
 * Author: Plugin Author
 * Text Domain: my-plugin
 */
```
All other things will be do on wp.org web site,
For example other translators can participate in translating your plugin on their language
https://translate.wordpress.org/
Example plugin: https://translate.wordpress.org/projects/wp-plugins/contact-form-7
I can help you to make your plugin RTL compatible too
https://codex.wordpress.org/Right-to-Left_Language_Support

Let me know if I can do anything in related subjects
Regards

**Comment by LaconicTranslator** [comment]
I'm ready to volunteer for translations to a couple of languages .

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
