### ISSUE TITLE
Can this plugin integrate with another service worker on my site?

### ISSUE THREAD

**Issue by a-aruga** [OneSignal/OneSignal-WordPress-Plugin#114]
As in the onesignal official document, it succeeded to import and run other service workers into both OneSignalSDKWorker.js.php and OneSignalSDKUpdaterWorker.js.php.
But is this affect when upgrading?
I would like to know the method that is not affected at the time of version upgrade.

[https://documentation.onesignal.com/docs/web-push-setup-faq#section-can-onesignal-integrate-with-another-service-worker-on-my-site-or-a-progressive-web-app-](url)

**Comment by jasonpang** [comment]
Hi @a-aruga,

Sorry for the delay in getting back to you. I'm having trouble understanding what method you're concerned with when the service workers upgrade. Can you please clarify?

**Comment by jkasten2** [comment]
@a-aruga There can only be one service worker for the top level of your site which the OneSignal Wordpress Plugin adds. If you need to add other service worker code you can add them to the `OneSignalSDKWorker.js.php` and `OneSignalSDKUpdaterWorker.js.php` files you have noted. However these files will be replaced when updating our plugin.

The docs you linked to only apply to our standalone javascript SDK.

**Comment by palmiak** [comment]
Hi 

Sorry to write in closed issue, but I have a simillar problem and I think that updating the code of the plugin is a wrong way to do it.

I think that adding filters is the best way to go. Here the best way would be:
```php
if ($onesignal_wp_settings["subdomain"] != "") {
  echo "oneSignal_options['subdomainName'] = \"" . $onesignal_wp_settings["subdomain"] . "\";\n";
}
else {
  $onesignal_path = apply_filters( 'onesignal_path', $current_plugin_url . "sdk_files/");
   echo "oneSignal_options['path'] = \"" . $onesignal_path. "\";\n";
}
```

Thanks to this we can change the path of SDK Files and update them in our theme. I think this should do the trick.
