### ISSUE TITLE
Notification automatically blocked

### ISSUE THREAD

**Issue by Ciao121** [OneSignal/OneSignal-WordPress-Plugin#116]
**Description:**

If  an user close the browser popup (just closes, not allowing or denying permission) the browsers automatically blocks the permission. And I get in the site's info "Notifications - Automatically blocked"

![automatically_blocked](https://user-images.githubusercontent.com/14965015/38731674-41d13224-3f13-11e8-9b29-5000382b6d41.jpg)

**Steps to Reproduce Issue:**

1. Enable "Automatically prompt new site visitors to subscribe to push notifications". This is not required. It happens also if the popup is opened from the bell.
2. Close the permission popup request without allowing/disallowing
3. Check the site's informations

iirc this should not be. Or is something changed?
Thank you!

**Comment by jasonpang** [comment]
Hi @Ciao121,

This is [a recently new feature](https://bugs.chromium.org/p/chromium/issues/detail?id=790035#c3) in Chrome. 

We recommend prompting for push permissions when the user has an incentive to subscribe. 

You can take a look at Google's [Permissions UX guide](https://docs.google.com/document/d/1WNPIS_2F0eyDm5SS2E6LZ_75tk6XtBSnR1xNjWJ_DPE/view) for some ideas.

**Comment by Ciao121** [comment]
Thank you very much!

**Comment by rv-mduarte** [comment]
Something very weird is that, if a user clicks on "block", i can see the website in the block list on chrome://settings/content/notifications. If a user just closes the prompt, it becomes blocked but is not listed in the blocked list.

A further issue with the permission prompt is that the prompt window has the block button on the right, and many people end up accidentally clicking on it by intuition (usually permissions are on the right). We do have a prompt with explanations about the push notifications before asking for permission, but around 20% of those who click "i want to receive notifications" end up blocking, which seems to be related. 

Anyone experiencing this?
