### ISSUE TITLE
Post's featured image doesn't work after the new update (1.16.7)

### ISSUE THREAD

**Issue by MohaTikiTaka** [OneSignal/OneSignal-WordPress-Plugin#117]
Hi, after updating the plugin to the last version **(1.16.7)**, the post's featured image no longer displays on notifications. A white square appears instead.

Regards.

**Comment by dboecker** [comment]
Same here, the SDK shows up that there is no icon transmitted to client:

`(Host) » notificationDisplay: 
{…}
content: "ABC This is my content"
heading: "THIS is my heading"
icon: undefined
id: "xxx"
url: "xxx"`

I'll get the same error by sending a notification over the WebUI, the only way it works normally is by sending a test notification via browser console.

Regards.

**Comment by dxflw** [comment]
same here no image wordpress issue

**Comment by jwilm** [comment]
We believe this has been resolved on our side. Please let us know if this continues to be an issue and we will investigate further.
