### ISSUE TITLE
Issues with Missing Bell & Notifications on Desktop

### ISSUE THREAD

**Issue by mibtp** [OneSignal/OneSignal-WordPress-Plugin#119]
**Description:**

https://www.hollywoodcharityauction.com

Hi, I believe I've set up everything properly and have set all the keys.  On Chrome I see the red bell and was able to subscribe myself, but once I added a new post and made sure the notification was on for that post, I did not see it on my computer.  Is it because I am the author?

Also, I added the proper key for safari and it is also active, but no red bell is showing up when you visit the site on safari.

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(any other information here)

**Comment by jkasten2** [comment]
@mibtp You should receive the notification as well when you make a post. As long as "Send notification on post publish" is check.
![image](https://user-images.githubusercontent.com/645861/39146034-6b6a9fb0-46ea-11e8-8392-407ff2ad42b4.png)

If you using a plugin to create post you will need to add this to the custom post types section of the OneSignal plugin.
![image](https://user-images.githubusercontent.com/645861/39146126-af8c8dd4-46ea-11e8-93b4-748a4e95c7c3.png)


I tested your site on Safari 11.0.1 on macOS 10.13 and was able to subscribe successfully. Note that Apple does NOT support push notifications on iOS.

**Comment by mibtp** [comment]
Thank you for the reply. I don't get notification, but glad you got.

Patrice

**Comment by jkasten2** [comment]
@mibtp Let me know if my reply didn't help and I can re-open the issue
