### ISSUE TITLE
Onesignal run to localhost ?

### ISSUE THREAD

**Issue by ankaramedya** [OneSignal/OneSignal-WordPress-Plugin#120]
Hello, onesignal run do is localhost ? If document share please happy

**Comment by ankaramedya** [comment]
Web push

**Comment by jkasten2** [comment]
@ankaramedya We have a guide for testing with localhost with the our javascript SDK below.
https://documentation.onesignal.com/docs/web-push-setup-faq#section-how-do-i-test-my-site-on-a-local-environment-

However we currently do no this option available for the Wordpress plugin

**Comment by rgomezp** [comment]
Closing due to no response.
