### ISSUE TITLE
send push notification to user 

### ISSUE THREAD

**Issue by AbbasTallaq** [OneSignal/OneSignal-WordPress-Plugin#122]
Hi, 
I have implemented onesignal notification, it's working perfectly. 
I have setup your plugin using Firebase to push nonfiction to mobile. Working great, thanks
however I want send push notification to single user a specific user, how can I achieve this

**Comment by AbbasTallaq** [comment]
seems, here it's dead nobody ..answers any thing ..

**Comment by jkasten2** [comment]
@AbbasTallaq There a few ways do this, depends on if you are looking to send notifications to your test devices or to single users in production.

For test users / devices you can follow this guide.
https://documentation.onesignal.com/docs/test-users

Or for a production user case
https://documentation.onesignal.com/docs/social-activity

**Comment by AbbasTallaq** [comment]
Hi,
I hav applied the code in my function.php,
however I getting this error 
"Segment You must use either segments OR include_player_ids, NOT both."

add_filter('onesignal_send_notification', 'onesignal_send_notification_filter', 10, 4);

function onesignal_send_notification_filter($fields, $new_status, $old_status, $post)
{
  // Change the notification's title, message, and URL,
  if($post->post_type == "product"){
 $fields['headings'] = array("en" => "new ");
  $fields['contents'] = array("en" => $post->post_title );
  $fields['include_player_ids'] = array("08ef263f.....");
  }


  //$fields['url'] = null;
  unset($fields['url']);  

   $fields['data'] = array("id" => $post->ID);

  $fields['isAndroid'] = true;

 


  return $fields;
}


} );

**Comment by jkasten2** [comment]
@AbbasTallaq You will need to `unset` `included_segments` as well as it is added by default

**Comment by AbbasTallaq** [comment]
Hi,
@jkasten2 , Thanks it works, 
However, can I fire push notification without check the checkbox, for ex. 
if received an order I want to fire push notification to the user automatically

**Comment by jkasten2** [comment]
@AbbasTallaq `onesignal_send_notification` will only fire when you make a post and have OneSignal checked as well.

To send a notification based on some other event you to make the REST API call directly. See the PHP example for doing so here
https://documentation.onesignal.com/reference#section-send-based-on-onesignal-playerids-create-notification

**Comment by 8owan** [comment]
is it possible to send notification to (registered / logged in) users only .. any help please !
