### ISSUE TITLE
Onsignal Wordpress plugin and Scheduled post

### ISSUE THREAD

**Issue by MarcoG75** [OneSignal/OneSignal-WordPress-Plugin#123]
I installed the wordpress plugin and it is working fine when I publish posts, but it does not work when posts are scheduled (to trigger a notification, I need to edit the post and click update).
Is anyone having the same issue?  Are there known incompatibilities with wordpress cron jobs?
Are there workaround to have the plugin trigger the notification when a scheduled post is published?

Thanks,
Marco

**Comment by vinaysamant** [comment]
hii @jkasten2 ..
i used this plugin for more than year and this funny thing started only recently, say 2-3 months. Untill then scheduled posts were covered properly.. 

still can you please guide us about writing that hook so that i can keep automation on..
thanks in advance..
