### ISSUE TITLE
Unable to Internationalize OneSignal Plugin

### ISSUE THREAD

**Issue by LaconicTranslator** [OneSignal/OneSignal-WordPress-Plugin#125]
**Description:**

The plugin is not ready for translation. 

**Steps to Reproduce Issue:**

1. Navigate to https://translate.wordpress.org/projects/wp-plugins/onesignal-free-web-push-notifications
2. Observe  "not properly prepared for localization" yellow message. 

**Anything else:**

It's not only a matter of  plugin internationalization, but also a matter of following WP community guidelines. 
BTW, OneSignal is awesome!
Good luck!

**Comment by jkasten2** [comment]
@LaconicTranslator At this time we don't plan on integrating translations into our plugin as we wont' be able to continuously maintain them. If there is something that can be changed with this plugin to be better compatible with external 3rd party translations I would be open to reviewing a PR for such. Thanks!
