### ISSUE TITLE
Subscription option does not show up on Mac Safari

### ISSUE THREAD

**Issue by wsjwong** [OneSignal/OneSignal-WordPress-Plugin#126]
**Description:**

1. Subscription option does not show up on Mac Safari

**Steps to Reproduce Issue:**

1. Create a project on OneSignal
2. Activate Safari Web ID from config
3. Install OneSignal plugin on my wordpress site
4. Activate the plugin and paste the Safari Web ID in configs
5. Subscription option shows up on Chrome but not on Mac Safari

Anything Else:
My site is http

**Comment by jkasten2** [comment]
@wsjwong Safari on macOS is supported. Can you double check that you selected WordPress when you setup the All Browsers platform?
![image](https://user-images.githubusercontent.com/645861/40214519-17572f54-5a10-11e8-805b-7f3038d46215.png)

Also double check that Safari is active and you have both the correct OneSignal app id and Safari web id entered in the OneSignal WordPress plugin.
![image](https://user-images.githubusercontent.com/645861/40214577-6972e670-5a10-11e8-834c-0479d65a2951.png)

Lastly I recommend contacting OneSignal support so they can take a look at your site to see if there is any configuration issue they can spot. You can also link your site here so we can take a look.
