### ISSUE TITLE
Page Links To incompatibility

### ISSUE THREAD

**Issue by Rayduxz** [OneSignal/OneSignal-WordPress-Plugin#127]
**Description:**

When using the "Page Links To" (https://wordpress.org/plugins/page-links-to/) plugin to set a custom URL for a post or a page, notifications from OneSignal sends you to the site dashboard (wp-admin).

**Steps to Reproduce Issue:**

1. Install "Page Links To" (https://wordpress.org/plugins/page-links-to/).
2. Begin to create a post or a page.
3. Set a custom URL for it at the "Page Links To" section.
4. Make sure OneSignal notification is enabled
5. Publish.
6. Click the push notification when you get it.
7. It sends you to your site dashboard (wp-admin).

**Anything else:**

Compatibility should be considered as the plugin has 200,000+ install and is compatible with the current WordPress version.

**Comment by jkasten2** [comment]
@Rayduxz We haven't had a chance to look into this, can you confirm if this is still an issue in their latest 3.0.1 version? We are also open to PRs if find the changes that are required. Thanks

**Comment by rgomezp** [comment]
Closing due to no response
