### ISSUE TITLE
Do not transmit the title of the entry in the notification with a large photo

### ISSUE THREAD

**Issue by Xen3** [OneSignal/OneSignal-WordPress-Plugin#129]
Hello! Wordpress plugin installed, lightspeed server, php 7.0 If you select a notification with a large photo, then in the notification there will not be a post entry, but only the site name, site address and photo.
![default](https://user-images.githubusercontent.com/39274015/40010463-7c6f15ce-57ad-11e8-97f2-c08ea5d89659.png)

If the message is without a large photo, then the title of the post is transmitted.

![3](https://user-images.githubusercontent.com/39274015/40010578-dc1c52ca-57ad-11e8-915a-7092da6efbbe.png)

This can somehow be fixed?

Thank you.

**Comment by fatsjohonimahnn** [comment]
@Xen3 You can set the notification title within the OneSignal Wordpress plugin settings.

If a title is not provided, our SDK will use the title from the last notification as web push requires a title set.

The post name will be the content of the notification.

Unfortunately there is not much you can control in terms of how the notifications are displayed.

Browsers take into account a lot of different factors that affect how notifications are displayed such as:

- Persisting Notifications
- Using images
- The operating system you are using
- Content length of title and message

For example, if you are using icons and have notification persistence enabled, then the message of the notification will be really short.

Please see our docs for more information on this: https://documentation.onesignal.com/docs/appearance#content
