### ISSUE TITLE
Error 404 Google Search Console

### ISSUE THREAD

**Issue by manu101010** [OneSignal/OneSignal-WordPress-Plugin#131]
Hi,

I have one error on my Google console that is https://www.example.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/ ; error 404

How can I fix it?

**Comment by jkasten2** [comment]
@manu101010 I recommend adding that url to your `robots.txt`. They files here don't need to be indexed.

**Comment by manu101010** [comment]
OK thanks
