### ISSUE TITLE
sendTags feature in Wordpress plugin

### ISSUE THREAD

**Issue by fayazara** [OneSignal/OneSignal-WordPress-Plugin#133]
**Description:**

The Wordpress plugin lacks support for sendTags feature which is important for wordpress to send customized notification for specific users. I tried adding this script as a user had mentioned [here](https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/101) he got it working by adding this script in his page, I did the same, it does not work.

<script data-cfasync="false" type="text/javascript"> OneSignal.sendTags({diabetes_in_url: true}); 		
</script>

**Steps to Reproduce Issue:**

 1.Add the above script in wordpress theme 
  2. Run the page
  4. Observe no tag is sent.

**Anything else:**
If you could provide me a workaround to use that would be great, I could try editing the wordpress plugin but I dont want to break it

**Comment by jkasten2** [comment]
@fayazara You need to wrap all calls to OneSignal functions with `OneSignal.push`. This is due to the OneSignal SDK loading asynchronous. Example:
```html
<script data-cfasync="false" type="text/javascript">
   OneSignal.push(function() {
      OneSignal.sendTags({diabetes_in_url: true});
   });
</script>
```

**Comment by alokshukla1510** [comment]
How to use above code when more than 6 blog category .
