### ISSUE TITLE
Breaks AMP for WP plugin.

### ISSUE THREAD

**Issue by Vidyut** [OneSignal/OneSignal-WordPress-Plugin#136]
**Description:**
AMP for WP plugin breaks if OneSignal is active. https://wordpress.org/plugins/accelerated-mobile-pages/

See this: https://wordpress.org/support/topic/one-signal-broken/
**Steps to Reproduce Issue:**

1. Install, activate, configure OneSignal
2. Install, activate, configure AMP for WP
3. AMP pages broken.

**Anything else:**

(any other information here)

**Comment by fatsjohonimahnn** [comment]
@Vidyut If you are still having this issue, please contact OneSignal Support with your app ID, the amp url, and a link to this ticket for further support.
