### ISSUE TITLE
PHP Deprecated on php 7.2

### ISSUE THREAD

**Issue by cristianciuberea** [OneSignal/OneSignal-WordPress-Plugin#137]
**Description:**

Hi,

We have php 7.2 on our server and we get this notification in ereror log:

PHP Deprecated:  Function create_function() is deprecated in/wp-content/plugins/onesignal-free-web-push-notifications/onesignal-widget.php on line 46

Could you fix it?

Thanks

**Comment by fatsjohonimahnn** [comment]
#110
