### ISSUE TITLE
Required Woocommere Wordpress Feature

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [OneSignal/OneSignal-WordPress-Plugin#138]
**Description:**

Woocommerce is a popular ecommerce plugin. We need the onesignal plugin to send out notifications to specific customers based on email address (for those logged in mobile device ionic cordova*) whenever there is a new order notes, order status changes and whenever new order is created. 

**Anything else:**

Hope that you will add this feature in wordpress for us to further fully utilize the product and service.

**Comment by jkasten2** [comment]
@ManigandanRaamanathan We don't plan to add integration specifically for Woocommerce at this time however our REST API can be used to send notification from your backend. It will take some PHP coding on your end but you could make a POST call to the `https://onesignal.com/api/v1/notifications` endpoint from those `Woocommerce` events. The OneSignal Create Notification documentation on the payload that needs to be sent to send a notification.
https://documentation.onesignal.com/reference#create-notification

**Comment by ManigandanRaamanathan** [comment]
@jkasten2  Can you provide example code for pushing android/ios mobile notification for specific email logged in users?

**Comment by jkasten2** [comment]
If you are setting the device's email with `OneSignal.setEmail(...)` in your app you can target a specific user from your backed with filters. The JSON for the request would look like this to send a push to a user with the matching email set in `"value"` below.
```json
{
  "app_id": "YOUR_ONESIGNAL_APP_ID",
  "filters": [{"field": "email", "value": "example@domain.com"}],
  "contents": {"en": "English Message"}
}
```

**Comment by ManigandanRaamanathan** [comment]
@jkasten2  I'm using currently cordova plugin. And how do I set the user email when logged in and remove when logged out. And can you share the code snippet for creating push notification for the specific email user using nodejs code?

**Comment by jkasten2** [comment]
@ManigandanRaamanathan From your Cordova app you will need to call `setEmail` when they login and `logoutEmail` if they logout.
https://documentation.onesignal.com/docs/cordova-sdk#section--setemail-

There is example code for NodeJs at the bottom of the Create Notification documentation if this is the backend you need to send the notification from
https://documentation.onesignal.com/reference#create-notification

**Comment by ManigandanRaamanathan** [comment]
@jkasten2  Thanks for the info. Will try and let you know.

**Comment by ManigandanRaamanathan** [comment]
@jkasten2  Can you provide example code in node js to push notification to specific email logged in device?

**Comment by jkasten2** [comment]
@ManigandanRaamanathan 
```javascript
var sendNotification = function(data) {
  var headers = {
    "Content-Type": "application/json; charset=utf-8",
    "Authorization": "Basic NGEwMGZmMjItY2NkNy0xMWUzLTk5ZDUtMDAwYzI5NDBlNjJj"
  };
  
  var options = {
    host: "onesignal.com",
    port: 443,
    path: "/api/v1/notifications",
    method: "POST",
    headers: headers
  };
  
  var https = require('https');
  var req = https.request(options, function(res) {  
    res.on('data', function(data) {
      console.log("Response:");
      console.log(JSON.parse(data));
    });
  });
  
  req.on('error', function(e) {
    console.log("ERROR:");
    console.log(e);
  });
  
  req.write(JSON.stringify(data));
  req.end();
};

// The logged in user to send a push notification to.
var emailTargetToSendPushTo = "example@domain.com";

var message = { 
  app_id: "5eb5a37e-b458-11e3-ac11-000c2940e62c",
  contents: {"en": "English Message"},
  filters: filters": [{"field": "email", "value": emailTargetToSendPushTo}],
};

sendNotification(message);
```

**Comment by ManigandanRaamanathan** [comment]
@jkasten2  Do I need to install any dependencies?

**Comment by ManigandanRaamanathan** [comment]
@jkasten2  the setEmail function is found in the onesignal cordova plugin ionic cordova native plugin. How to get it work?

**Comment by fatsjohonimahnn** [comment]
@ManigandanRaamanathan You can see this method in our documentation with example code here: https://documentation.onesignal.com/docs/cordova-sdk#section--setemail-

Make sure you are using at least version 2.3.2 of our Cordova/Ionic SDK but we recommend our latest version. 

For further questions, please contact us through our support channel.

**Comment by ManigandanRaamanathan** [comment]
@fatsjohonimahnn  I'm using version 2.3.3 . But the setEmail function is not being executed properly

**Comment by ManigandanRaamanathan** [comment]
@jkasten2 @fatsjohonimahnn  Finally made it work. In ionic importing the non native plugin without official oc is a hassle for novice like me.

Got 1 doubt about the setEmail function. Is the system generates new player id whenever the user is logged out while storing both mobile device id? In anyways is the device able to receive notification on a mobile app for the logged out email id?

**Comment by ManigandanRaamanathan** [comment]
@jkasten2  @fatsjohonimahnn  Why am I not able to set same email to different player Id's? from different devices when I'm trying to set the same email eg. Test@gmail.com. The previous user email get "-" instead of the same email.

**Comment by jkasten2** [comment]
@ManigandanRaamanathan When you call `setEmail` it will set the email on field on that player record. As well as create a new email player id if one does not exist already.

I recommend contacting OneSignal support with more details about the problem you need to solve and the exact issues you are running into.

**Comment by lgdelai** [comment]
Hello.

I apologize for reactivating this topic almost a year later.

I have a similar question.  I need to send a notification to a customer when his order leaves for delivery, that is, when the order status changes to "out-for-delivery". 

It would be possible that whenever the status of an order was changed to "out-for-delivery" a push notification was sent to the customer who placed the order. 

For example: If the onesignal uses the customer's email to send a notification to this specific customer, it might be possible to get this email through the order number that had its status changed. 
And then send the notification to the correct customer?

Where would I start in order to implement this solution, which may even be used in the future in onesignal, given its importance for delivery sites.

I currently have onesignal up and running on my website.
