### ISSUE TITLE
The way to let the manifest file autogenerated by onesignal not to flush in head section

### ISSUE THREAD

**Issue by houjiro** [OneSignal/OneSignal-WordPress-Plugin#139]
**Description:**
Hi developing team. I'm appreciating this awesome plugin so much.

I have a question to let the manifest file autogenerated by onesignal not to flush in head section. Because I owned multilingual wordpress website and want to write link in head section directly to show different manifests in each language.

I know "Custom manifest.json URL" field in admin page, but I can't write 2 manifest links for different language page.

So I guess if this plugin has the filter to deactivate "insert_onesignal_header_manifest" function, I can show one manifest written directly by me without autogenerated manifest file by onesignal plugin.
Is there good way to do this?

Please advise

**Comment by rgomezp** [comment]
Closing due to no response. Please feel free to reply if you have further questions.
