### ISSUE TITLE
Notification 404 error on Samsung browser

### ISSUE THREAD

**Issue by cesar-regio** [OneSignal/OneSignal-WordPress-Plugin#140]
**Description:**

When I receive a notification on my Samsung Browser I get a 404 error.

**Steps to Reproduce Issue:**

  1. I publish the notification.
  2. I receive the notification on my Samsung browser.
  3. The link displays a 404 error.
  4. Observe no notification is sent.

**Anything else:**

It works fine in other browsers, except the native browser from my Samsung phone.

**Comment by jkasten2** [comment]
@cesar-regio Can you make sure you are testing with the latest 7.2.10.33 version of the Samsung Internet browser? Samsung has made a number of updates to their browser that may have effected such as updates to their server worker implementation.

If this does not help please contact OneSignal support providing your notification id and app id so they can look into the issue. Thanks
