### ISSUE TITLE
uBlock Origin 1.16.0 blocks OneSignal

### ISSUE THREAD

**Issue by sandrodz** [OneSignal/OneSignal-WordPress-Plugin#142]
**Description:**

uBlock Origin 1.16.0 blocks OneSignal, no notification is displayed.

**Steps to Reproduce Issue:**

1. Install and configure plugin
2. Install uBlock Origin 1.16.0 in safari
3. check homepage - bell is not displayed, user is not asked to subscribe via browser

**Comment by jkasten2** [comment]
@sandrodz Thanks for letting us know. It looks like a few other push provides are blocked too in their list too. There isn't much we can do in this case if they choose to block the OneSignal domain. I recommend asking uBlock if they can remove cdn.onesignal.com as it is an important tool you use to provide updates to your users. In the end though it will be their decision.

**Comment by kkinder** [comment]
I'm looking for a way to block all those "Allow notifications" popups. Can someone tell me which ublock origin filter list works against OneSignal and other similar embeds?
