### ISSUE TITLE
About Mannually Operating the One Signal Notification For Wix Website...

### ISSUE THREAD

**Issue by Pd08111997** [OneSignal/OneSignal-WordPress-Plugin#149]
Hi, 

I have a Wix website and I want to connect it's "Get access Now" Button To A Push Notification Software- ONESIGNAL.

I want to customize it with a website Button...

It must Work Like This--

If Some One Clicks "Notify Button" 

then the Push Notification Bar Must Appear 

and Then Rest will be Handled By the ONESIGNAL platform.

Is this Possible On Wix Because I have Got the Code For Wordpress but I am Not Sure About Wix, So If I can Get Some Help...
![fiverr](https://user-images.githubusercontent.com/44059501/46807466-9f330480-cd87-11e8-9809-c837dfa3f7b3.JPG)

**Comment by jkasten2** [comment]
@Pd08111997 All the details on customizing this prompt can be found below.
https://documentation.onesignal.com/docs/custom-link-prompt

Since your question isn't related to Wordpress I recommend contacting OneSignal support if you have more questions on integrating with Wix
