### ISSUE TITLE
 send notification to (registered / logged in) users only

### ISSUE THREAD

**Issue by 8owan** [OneSignal/OneSignal-WordPress-Plugin#152]
is it possible to send notification to (registered / logged in) users only .. any help please !

**Comment by jkasten2** [comment]
@8owan I recommend using tags to do this. You can tag the user when they login with the guide below. It will require adding some javascript code to your site.
https://documentation.onesignal.com/docs/add-user-data-tags

Please contact OneSignal support if you have more questions on setting up or using tags.
