### ISSUE TITLE
Custom badge icon

### ISSUE THREAD

**Issue by andreafrison** [OneSignal/OneSignal-WordPress-Plugin#153]
How can I add badge icon in this plugin?

**Comment by jkasten2** [comment]
There isn't an option build into the WordPress configuration page for this. Please see the following guide on adding custom fields to notification the OneSignal WordPress plugin generates.
https://documentation.onesignal.com/docs/web-push-wordpress-faq#section-customizing-wordpress-plugin-behavior

See the appearance and attachments sections on the OneSignal REST API documentation on what fields you can your icon / image to.
https://documentation.onesignal.com/reference#section-attachments
https://documentation.onesignal.com/reference#section-appearance

**Comment by rgomezp** [comment]
Closing due to no response
