### ISSUE TITLE
403: OneSignalSDKWorker.js.php

### ISSUE THREAD

**Issue by mattbodell** [OneSignal/OneSignal-WordPress-Plugin#154]
OneSignalSDKWorker.js.php returns a 403 error. 

I have searched and found similar issues that are plugin related but I have disabled all plugins and cleared all caches and this still seems to be the issue.

You can see here: https://nursingnotes.co.uk.

I have tried a different theme, plugins, changing directory permissions - everything.

Your help would be much appreciated.

**Comment by fatsjohonimahnn** [comment]
@mattbodell We have received your ticket through our main support channel and will help you there. 

For anyone else with this issue, please review our Web Push Troubleshooting guide here: https://documentation.onesignal.com/docs/troubleshooting-web-push#section-service-worker-404-and-403-errors

If you are still having issues after looking through the above troubleshooting guide, reach out to the OneSignal support channel with your OneSignal app ID.
