### ISSUE TITLE
Merge Service Worker Action Hook

### ISSUE THREAD

**Issue by Timbral** [OneSignal/OneSignal-WordPress-Plugin#158]
**Description:**

I'm looking to merge my custom service worker with OneSignal's service workers. While the WordPress plugin can be edited, specifically the OneSignalSDKWorker.js.php file, to allow for this, all the plugin's files will be overwritten on update. While I can regenerate OneSignalSDKWorker.js.php on plugin activation or another hook, it would be simpler and fault tolerant to offer a simple hook that runs importScripts() on any 3rd party service worker passed in.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
