### ISSUE TITLE
Multiple Pushs since Wordpress 5

### ISSUE THREAD

**Issue by taker93** [OneSignal/OneSignal-WordPress-Plugin#161]
**Description:**

Since updating to Wordpress 5.0 the plugin is sending the push notification multiple times. We're using the wordpress plugin with an must-used-Plugin as described on your homepage. Nothing special.

**Steps to Reproduce Issue:**

1. Log in to WordPress.
2. Create new Post.
3. Click on publish.
4. Change a line of text and "publish" again.
5. Repeat step 4 multiple times.
Result: Every click on "publish" or "refresh" causes a new notification.

Maybe its because the check on "Send notification on post publish" is not removed after publishing.

**Comment by rgomezp** [comment]
Hello taker93,
Thanks for bringing this up. I was able to reproduce the issue. You are correct in that the "Send notification on post publish" check is only removed after you navigate away from the post's page. We will address this as soon as we can.
