### ISSUE TITLE
Push Notification on post update

### ISSUE THREAD

**Issue by firojghimire** [OneSignal/OneSignal-WordPress-Plugin#166]
**Description:**

OneSignal Push shows a message 'OneSignal Push: A notification was sent, but there were no recipients.' while updating existing post in  wordpress even though I have recipients. Push notifications are working fine for new posts.
**Steps to Reproduce Issue:**

The issue seems to have appeared after the recent update of version 1.16.12. Before that, push notifications on post updates were working fine.
**Anything else:**

**Comment by rgomezp** [comment]
Hello @firojghimire 
We are working on a fix for this that should be out very soon. In the meantime, slightly changing the title of the post should allow you to re-send a notification for a post.

Best,
Rodrigo

**Comment by rgomezp** [comment]
@firojghimire Just wanted to follow up with you regarding your issue. We released a new version of the plugin yesterday that should resolve this. Please note that sending updates for same posts are rate-limited to 1/hour! Cheers
