### ISSUE TITLE
Wordpress issue: manifest.json.php unexpected token on line 1

### ISSUE THREAD

**Issue by DimChristodoulou** [OneSignal/OneSignal-WordPress-Plugin#168]
**Description:**

I'm working on an HTTPS Wordpress website with the OneSignal Push Notifications plugin. When the page loads, I get the following error in the manifest.json.php file:

`Manifest: Line: 1, column: 1, Unexpected token.`

Afterwards, if I click the notification bell button, I get the following errors:

`The path of the provided scope ('/') is not under the max scope allowed ('/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.`

`Failed to load resource: net::ERR_INSECURE_RESPONSE`

`[Service Worker Installation] Installing service worker failed SecurityError: Failed to register a ServiceWorker: The path of the provided scope ('/') is not under the max scope allowed ('/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.`

Things I've tried so far:

- Modify .htaccess file to 'Allow from all' the `OneSignalSDKUpdaterWorker.js.php` , `OneSignalSDKWorker.js.php`, `manifest.json.php`
- Change permissions on the same files.

Since I've read that there are some issues when this plugin works together with third party CDN and caching plugins, I have to mention that **there are no such plugins (CDN or cache) running** on the website.

**Comment by rgomezp** [comment]
Hello,
Have you modified the manifest file itself at all? Also, please make sure that the SDK files are accessible by visiting them in your browser:

yoursite.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKWorker.js.php
yoursite.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKUpdaterWorker.js.php
yoursite.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/manifest.json.php

Best,
Rodrigo

**Comment by DimChristodoulou** [comment]
Hello,
Thank you for the reply.
I have already verified that the SDK files can be accessed through the browser and I have not modified the manifest in any way.

**Comment by rgomezp** [comment]
This sounds to me like a service worker scope issue. Perhaps your service worker is not in the right scope due to your unique WP setup or a conflicting plugin. Check out this [thread](https://stackoverflow.com/questions/35780397/understanding-service-worker-scope) discussing service worker scope. Hopefully you can gain some insight into what is happening

**Comment by DimChristodoulou** [comment]
Thank you for the thread, it was really helpful. However, I still have a few questions.

1. If I move the worker SDK files in the root folder of the directory (or any other subdirectory for this matter), won't this prevent the plugin from loading correctly (since it's depending on the WP plugin manager).
2. Correct me if I'm wrong, but the worker issues have little to do with the error in the manifest file. Will this error prevent the SDK files from running?

I should mention that I have already tried to move the script files to the website root folder and nothing happened.

Thank you for your time.

**Comment by rgomezp** [comment]
Hello,
1. Yes, I would imagine that moving the files would break something.
2. Yes, you need to make sure that the manifest file has no issues in order for OneSignal to work correctly

I am not sure what is happening with your site. If you would like, you can ping us through the support channels on the OneSignal homepage so you can share with us your site and we can take a closer look at what may be happening.
