### ISSUE TITLE
Fatal error: Uncaught Error: Cannot use object of type WP_Error as array

### ISSUE THREAD

**Issue by sdennis69** [OneSignal/OneSignal-WordPress-Plugin#173]
**Description:**

Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /home/nginx/domains//public/wp-content/plugins/onesignal-free-web-push-notifications/onesignal-admin.php:755Stack trace: #0 /home/nginx/domains/public/wp-content/plugins/onesignal-free-web-push-notifications/onesignal-admin.php(840): OneSignal_Admin::send_notification_on_wp_post('publish', 'auto-draft', Object(WP_Post)) #1 /home/nginx/domains/public/wp-includes/class-wp-hook.php(286): OneSignal_Admin::on_transition_post_status('publish', 'auto-draft', Object(WP_Post)) #2 /home/nginx/domains/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /home/nginx/domains/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /home/nginx/domains/public/wp-includes/post.php(4202): do_action('transition_post...', 'publish', 'auto-draft', Object(WP_Post)) #5 /home/nginx/domains/public/wp-includes/post.php(3662): wp_transition_post_status(' in /home/nginx/domains/public/wp-content/plugins/onesignal-free-web-push-notifications/onesignal-admin.php on line 755

**Steps to Reproduce Issue:**

  1. Log in to WordPress.
  2. Click Post -> Add New
  3. Click Publish
  4. Post is created, no notification is sent.

**Anything else:**

(any other information here)

**Comment by chroust** [comment]
We have same problem:

[11-Mar-2019 17:38:11 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in www/wp-content/plugins/onesignal-free-web-push-notifications/onesignal-admin.php:755
Stack trace:
#0 www/wp-content/plugins/onesignal-free-web-push-notifications/onesignal-admin.php(840): OneSignal_Admin::send_notification_on_wp_post('publish', 'draft', Object(WP_Post))
#1 www/wp-includes/class-wp-hook.php(286): OneSignal_Admin::on_transition_post_status('publish', 'draft', Object(WP_Post))
#2 www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 www/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 www/wp-includes/post.php(4128): do_action('transition_post...', 'publish', 'draft', Object(WP_Post))
#5 www/wp-includes/post.php(3588): wp_transition_post_status('publish' in www/wp-content/plugins/onesignal-free-web-push-notifications/onesignal-admin.php on line 755

Reproduce issue is same as @sdennis69 wrote with one exception. Our notifications are sent.

**Comment by chroust** [comment]
I found temporary fix. Here is same error as we reported https://wordpress.org/support/topic/help-with-fatal-error-uncaught-error/ and here is the temporary fix https://github.com/OneSignal/OneSignal-WordPress-Plugin/tree/notices

**Comment by rgomezp** [comment]
Hello,
We have released an update with fixes to both those errors. Thank you for your patience!

**Comment by chroust** [comment]
Thanks for the quick response guys 👍

**Comment by sdennis69** [comment]
Yes, thanks so much!

**Comment by rgomezp** [comment]
No problem. If you enjoy our product, please consider taking just a moment to [leave us a review](https://wordpress.org/support/plugin/onesignal-free-web-push-notifications/reviews/#new-post).

Thanks!
