### ISSUE TITLE
Trying to get property 'ID' of non-object in public_html/wp-content/plugins/onesignal-free-web-push-notifications/onesignal-admin.php on line 17

### ISSUE THREAD

**Issue by stefa98** [OneSignal/OneSignal-WordPress-Plugin#176]
**Description:**
Trying to get property 'ID' of non-object in public_html/wp-content/plugins/onesignal-free-web-push-notifications/onesignal-admin.php on line 17

Error Console: notice.js?ver=1.1:3 OneSignal Push: couldn't load wp.data. https://bit.ly/2F4G0bt
(anonymous) @ notice.js?ver=1.1:3
Access to fetch at 'https://onesignal.com/api/v1/notifications/...' from origin 'https://www.website.it' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://onesignal.com/api/v1/notifications/... with MIME type text/plain. See https://www.chromestatus.com/feature/... for more details.
OneSignalSDKWorker.js.php?appId=... Uncaught (in promise) TypeError: Failed to fetch
Promise.then (async)
(anonymous) @ ServiceWorker.js:71
OneSignalSDKWorker.js.php?appId=... Uncaught (in promise) TypeError: Failed to fetch

I have updated to the latest version and it gives me this problem.

**Steps to Reproduce Issue:**

  1. Log in to WordPress.
  2. Update the plugin: OneSignal-WordPress-Plugin

**Comment by Dibbyo456** [comment]
Yup. Having the same issue.

**Comment by rgomezp** [comment]
We have released an update. Can you please test? Thanks

**Comment by Dibbyo456** [comment]
Yup. Everything is working fine now.. (had to clear browser caches though).

**Comment by stefa98** [comment]
The problem persists. The error has not been resolved.

**Comment by Dibbyo456** [comment]
You need to clear cache or try different browser.

**Comment by vectrus** [comment]
I can confirm the update doesn't change the error. I do not use any Yoast SEO plugin. Nor does disabling other plugins have any avail.

**Comment by rgomezp** [comment]
@vectrus 
good to hear! this is exactly what we did. feel free to contribute as this project is open source!
