### ISSUE TITLE
'ID' of non-object in 1.16.16

### ISSUE THREAD

**Issue by altendorfme** [OneSignal/OneSignal-WordPress-Plugin#179]
**Description:**
```
Notice:  Trying to get property 'ID' of non-object in \wp-content\plugins\onesignal-free-web-push-notifications\onesignal-admin.php on line 17
```
**onesignal-admin.php**
```
wp_localize_script('notice_script', 'ajax_object', array('ajax_url' => admin_url("admin-ajax.php"), 'post_id' => $post->ID));
```

**Steps to Reproduce Issue:**
  1. Log in to WordPress.
  2.

**Comment by rgomezp** [comment]
please update to the new version and clear your cache (force-refresh)

**Comment by altendorfme** [comment]
The error appears in the development environment, it does not have any type of cache and I am already using the latest version 1.16.16
