### ISSUE TITLE
Bug WPBakery Page Builder 5.7

### ISSUE THREAD

**Issue by Camilo517** [OneSignal/OneSignal-WordPress-Plugin#183]
It just does not load the editor
http://prntscr.com/n3u39n
In this version the plugin works well OneSignal-WordPress-Plugin 1.16.14
https://wordpress.org/support/topic/incompatibilidad-con-wpbakery-page-builder/

**Comment by rgomezp** [comment]
This issue was resolved with the past two releases. Please update your plugin
