### ISSUE TITLE
OneSignal push error -- no subscribers or you hit the rate-limit

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [OneSignal/OneSignal-WordPress-Plugin#192]
I'm using Version 1.17.3 with WordPress 5.1.1
I have about 500 subscribers and today I got this error message when trying to post something new.

> OneSignal Push: there were no recipients. You either 1) have no subscribers yet or 2) you hit the rate-limit. Please try again in an hour. Learn more: https://bit.ly/2UDplAS

Why am I getting this error when this was the first post I made this week?

**Comment by rgomezp** [comment]
Hello,
Thanks for your question. Is this something you can reproduce? Please follow [these instructions](https://documentation.onesignal.com/docs/troubleshooting-wordpress-web-push#section-debugging-with-gutenberg) to debug with Gutenberg.

Best

**Comment by fiyan0070** [comment]
I got the same error...

**Comment by Karlheinzniebuhr** [comment]
@rgomezp I haven't be able to reproduce it as I am not running Wordpress locally in Development mode

**Comment by rgomezp** [comment]
@Karlheinzniebuhr ,
If you follow the instructions I included, you will get a more detailed error message that will help us understand what exactly is happening in your backend.

Karl, how are you running Wordpress?

**Comment by fiyan0070** [comment]
My sites are hosted on ionos servers.

**Comment by rgomezp** [comment]
We released a new version of the plugin that has lowered the rate-limit to two minutes. Please try again and let us know if you are still seeing the issue.

**Comment by Karlheinzniebuhr** [comment]
> are you running Wo

I'm running wordpress in the cloud, not locally. So I'm not sure how to get the error log but I will try to obtain it if this error is still present. Thanks!

**Comment by rgomezp** [comment]
I see @Karlheinzniebuhr . You should be able to test it without looking at the logs. Simply make a post and see what notice is displayed after posting

**Comment by rgomezp** [comment]
Closing due to no response
