### ISSUE TITLE
App id cannot be empty

### ISSUE THREAD

**Issue by rodrigoetoh** [OneSignal/OneSignal-WordPress-Plugin#194]
**Description:**

Whenever I try to update subscription tags in Chrome, Opera (both on Windows), this error occurs when I use sendTag(s): **App id cannot be empty**
This error don't seem to occur in Firefox nor Edge.

**Steps to Reproduce Issue:**

1. Open https://pwa.nerau.com.br/
2. Accept Notifications.
3. Once you accept, you SHOULD receive a welcome notification, but you don't. And the sendTags throws the **App id cannot be empty**

**Anything else:**

The error occurred in Chrome version:  Version 74.0.3729.157 (Official Build) (64-bit)

Chrome on Android is OK;
Chrome on Mac is OK;
Safari on Mac doesn't even show the notifications popup (but that's another subject);

**Comment by rgomezp** [comment]
Hello,
I wasn't able to reproduce your issue. Please make sure you have set up OneSignal correctly in your Wordpress configuration. Also, do you have any other service workers?

**Comment by rodrigoetoh** [comment]
> Hello,
> I wasn't able to reproduce your issue. It worked for me. Please make sure you have set up OneSignal correctly in your Wordpress configuration. Also, do you have any other service workers?

Hello!

It seems to have resolved itself, somehow... That's awkward... Thanks, anyway!

**Comment by rgomezp** [comment]
I'm glad! No problem
