### ISSUE TITLE
Notifications for Mobile Apps and Browsers At Same Time

### ISSUE THREAD

**Issue by ohadza1** [OneSignal/OneSignal-WordPress-Plugin#197]
**Description:**
Hello,
We have a Wordpress website and working with OneSignal for few years. We love the service! We are now working on new Android and iOS applications using Flutter. The Flutter package works well and we managed to get notification once a new article is published. 

The problem, as many indicated, is when receiving a notification in Android or iOS, clicking on it opens the post in the browser. To overcome this, we used this [guide in OneSignal documentation](https://documentation.onesignal.com/docs/web-push-wordpress-faq#section-opening-web-and-mobile-notifications-in-the-browser-and-app).

After following the guide and implementing the solution, we can receive notification in mobile apps as expected, but we encounter a new problem: The push notification received in browsers stopped opening the specific post pushed and opens only the main website page.

So the current status is: Once a post is published -> push notifications are sent to mobile app and browsers -> push notifications received in mobile app and browsers -> on clicking the notification -> apps opened properly, but web opens the home page and not the expected post as before the change following the Docs guide.

**Steps to Reproduce Issue:**

1. Follow the [guide](https://documentation.onesignal.com/docs/web-push-wordpress-faq#section-opening-web-and-mobile-notifications-in-the-browser-and-app)
2. Publish a new post with push enabled

**Comment by rgomezp** [comment]
Hello,
Did you add the following code?
```php
<?php
add_filter('onesignal_send_notification', 'onesignal_send_notification_filter', 10, 4);

function onesignal_send_notification_filter($fields, $new_status, $old_status, $post)
{
    /* Goal: We don't want to modify the original $fields array, because we want the original web push notification to go out unmodified. However, we want to send an additional notification to Android and iOS devices with an additionalData property.
    */
    $fields_dup = $fields;
    $fields_dup['isAndroid'] = true;
    $fields_dup['isIos'] = true;
    $fields_dup['isAnyWeb'] = true;
    $fields_dup['isWP'] = false;
    $fields_dup['isAdm'] = false;
    $fields_dup['isChrome'] = false;
    $fields_dup['data'] = array(
        "myappurl" => $fields['url']
    );
    /* Important to unset the URL to prevent opening the browser when the notification is clicked */
    unset($fields_dup['url']);
    /* Send another notification via cURL */
    $ch = curl_init();
    $onesignal_post_url = "https://onesignal.com/api/v1/notifications";
    /* Hopefully OneSignal::get_onesignal_settings(); can be called outside of the plugin */
    $onesignal_wp_settings = OneSignal::get_onesignal_settings();
    $onesignal_auth_key = $onesignal_wp_settings['app_rest_api_key'];
    curl_setopt($ch, CURLOPT_URL, $onesignal_post_url);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Content-Type: application/json',
        'Authorization: Basic ' . $onesignal_auth_key
    ));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HEADER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields_dup));
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

    // Optional: Turn off host verification if SSL errors for local testing
    // curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);

    /* Optional: cURL settings to help log cURL output response
    curl_setopt($ch, CURLOPT_FAILONERROR, false);
    curl_setopt($ch, CURLOPT_HTTP200ALIASES, array(400));
    curl_setopt($ch, CURLOPT_VERBOSE, true);
    curl_setopt($ch, CURLOPT_STDERR, $out);
    */
    $response = curl_exec($ch);
    /* Optional: Log cURL output response
    fclose($out);
    $debug_output = ob_get_clean();
    $curl_effective_url = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
    $curl_http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $curl_total_time = curl_getinfo($ch, CURLINFO_TOTAL_TIME);
    onesignal_debug('OneSignal API POST Data:', $fields);
    onesignal_debug('OneSignal API URL:', $curl_effective_url);
    onesignal_debug('OneSignal API Response Status Code:', $curl_http_code);
    if ($curl_http_code != 200) {
    onesignal_debug('cURL Request Time:', $curl_total_time, 'seconds');
    onesignal_debug('cURL Error Number:', curl_errno($ch));
    onesignal_debug('cURL Error Description:', curl_error($ch));
    onesignal_debug('cURL Response:', print_r($response, true));
    onesignal_debug('cURL Verbose Log:', $debug_output);
    }

    */
    curl_close($ch);
    return $fields;
}```

**Comment by rgomezp** [comment]
Try adding this line before the `unset`:   	`$fields_dup['web_url'] = $fields_dup['url'];`

**Comment by ohadza1** [comment]
Thank you @rgomezp !
It worked. May I highly suggest to change this in the documentation.
As a long time website owner, and I guess many others, this is the best use-case if you use OneSgnal for web and apps.

**Comment by rgomezp** [comment]
Hello @ohadza1 ,
That's great to hear! I already updated the documentation. Thank you so much for bringing this up!

**Comment by kazziosoftware** [comment]
Hi. I'm using the Wordpress plugin for OneSignal and followed the instructions as per the link above and read this thread, but, after the latest update, the plugin is not send any Push for Web users, only mobile, because the push is being sent via curl.
I can't see anything special on logs and if I remove the curl part of the script, the push get send to Web users.
Any idea on what could be wrong? If I keep using outdated plugin, it works.

**Comment by rgomezp** [comment]
@kazziosoftware ,
Have you taken a look at your Wordpress logs? I still need to update that code snippet to use the HTTP api and not curl. Best

**Comment by kazziosoftware** [comment]
@rgomezp Thanks. Can you share with me a snippet of the code? Another thing I'm suspecting is that there a real limit for sending consecutive pushes - because curl is working fine for Mobile and then we're using the "native" system for Web and is failing. If we send only for Web (using the native plugin) works. (the difference in my code is `$fields_dup['isAnyWeb'] = true;` that is set to false.

**Comment by rgomezp** [comment]
@kazziosoftware ,
```php
<?php
    add_filter('onesignal_send_notification', 'onesignal_send_notification_filter', 10, 4);
    function onesignal_send_notification_filter($fields, $new_status, $old_status, $post) {
        /* Goal: We don't want to modify the original $fields array, because we want the original web push notification to go out unmodified. However, we want to send an additional notification to Android and iOS devices with an additionalData property.
         *     */
        $fields_dup = $fields;
        $fields_dup['isAndroid'] = true;
        $fields_dup['isIos'] = true;
        $fields_dup['isAnyWeb'] = true;
        $fields_dup['isWP'] = false;
        $fields_dup['isAdm'] = false;
        $fields_dup['isChrome'] = false;
        $fields_dup['data'] = array("myappurl" => $fields['url']);
        /* Important to set web_url to support opening through both mobile and browser*/
        $fields_dup['web_url'] = $fields_dup['url'];
        /* Important to unset the URL to prevent opening the browser when the notification is clicked for mobile app users */
        unset($fields_dup['url']);
        $onesignal_post_url = "https://onesignal.com/api/v1/notifications";
        /* Hopefully OneSignal::get_onesignal_settings(); can be called outside of the plugin */
        $onesignal_wp_settings = OneSignal::get_onesignal_settings();
        $onesignal_auth_key = $onesignal_wp_settings['app_rest_api_key'];
        $request = array("headers" => array("content-type" => "application/json;charset=utf-8", "Authorization" => "Basic " . $onesignal_auth_key), "body" => json_encode($fields_dup), "timeout" => 60);
        $response = wp_remote_post($onesignal_post_url, $request);
        if (is_wp_error($response) || !is_array($response) || !isset($response['body'])) {
            $status = $response->get_error_code();
            $error_message = $response->get_error_message();
            error_log("There was a " . $status . " error returned from OneSignal when sending to mobile users: " . $error_message);
            return;
        }
        return $fields;
    }

```

**Comment by kazziosoftware** [comment]
Cool. Thanks. I just changed `$fields_dup['isAnyWeb']` to true and worked.
But will update to use the HTTP API to prevent future problems.

**Comment by rochapablo** [comment]
Just a question... why not have this already inside the plugin, plus mobile fields inside the setup?
