### ISSUE TITLE
Formatting the code

### ISSUE THREAD

**Issue by szepeviktor** [OneSignal/OneSignal-WordPress-Plugin#206]
Hello!

Please consider formatting the code according to [WPCS](https://github.com/WordPress/WordPress-Coding-Standards#installation), it takes 3 minutes, e.g.

`vendor/bin/phpcs --standard=WordPress-Core onesignal-widget.php`

That way you spot errors much easier!

**Comment by szepeviktor** [comment]
and `vendor/bin/phpcs --standard=WordPress-Extra onesignal-widget.php` tells you where to secure the code

**Comment by szepeviktor** [comment]
```
$ ~/src/wpcs/vendor/bin/phpcbf --standard=WordPress-Core onesignal-admin.php

PHPCBF RESULT SUMMARY
------------------------------------------------------------------------------------
FILE                                                                FIXED  REMAINING
------------------------------------------------------------------------------------
/home/viktor/tmp/OneSignal-WordPress-Plugin/onesignal-admin.php     2150   117
------------------------------------------------------------------------------------
A TOTAL OF 2150 ERRORS WERE FIXED IN 1 FILE
------------------------------------------------------------------------------------
```

**Comment by rgomezp** [comment]
Hi. Thanks for your suggestion. We have done this and will be reflected in the [upcoming version of the plugin](https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/217). Cheers

**Comment by szepeviktor** [comment]
You're welcome.
