### ISSUE TITLE
(Feature request) Allow target a specific segment for each post webpush, rather than try to send to all subscribers

### ISSUE THREAD

**Issue by AlbanL74fr** [OneSignal/OneSignal-WordPress-Plugin#211]
Better targetting means better CTR. From the dashboard, OneSignal already offers possibilities to create segments of subscribers, so it's just a pity that these segments can't be targetted when the plugin WP is used.

As the blog post author, I would like to be able to activate the sending of webpush notification to execute once my post is published (already possible) while also having a select box to choose what segments I want to send to
If a subscribers is in two segments selected or more, he/she would receive this web push only one time.

**Comment by rgomezp** [comment]
Thanks for your suggestion. We will track internally
