### ISSUE TITLE
How to hook into OneSignal plugin in order to hide metabox for published article

### ISSUE THREAD

**Issue by AlbanL74fr** [OneSignal/OneSignal-WordPress-Plugin#213]
Hi, 
Been looking into the doc for that but not sure how to do it. I am trying to keep the metabox OneSignal only for draft articles, not yet published.
That means I want to alter the plugin to hide it on any post that is already published, so no notification can ever been sent mistakenly on post updates. 
In my opinion, this should be part of settings, to accomodate authors and editors workflow amd avoid misuse.

Can the plugin author explain me how to do that? Thanks

**Comment by rgomezp** [comment]
Thanks for your suggestion. The original author is no longer available for an explanation. We will mark this as a feature request and track it internally. Cheers
