### ISSUE TITLE
"Action Required to integrate SuperPWA with OneSignal"

### ISSUE THREAD

**Issue by TwoFlags** [OneSignal/OneSignal-WordPress-Plugin#218]
![One Signal screen shot](https://user-images.githubusercontent.com/35459669/69466996-e4c44e00-0d4b-11ea-9d2b-51db21b2c7eb.png)

**Description:**

"Action Required to integrate SuperPWA with OneSignal"

**Steps to Reproduce Issue:**

1. Log in to WordPress
2. Look at the top of any screen
3. You'll see the box shown in the attached screen shot. (At least I do)

**Anything else:**

I'm told that the latest version of your plugin no longer requires this action. Yet, I'm seeing this error message.

In a message to me, support said: "The manifest.json file is not required for web push anymore. We have removed this from our setup. SuperPWA provides its own Manifest.json file. If you are seeing an error you can make sure to remove this line from the init code:
<link rel="manifest" href="/manifest.json"> 
Any reference to the manifest will not hurt your site, you can remove it if you want."

Thing is, I just downloaded the plugin and installed it a year ago. Now I have 2,000 subscribers and am not a coder. I don't know an init file from my ass. I just don't want to see this error message every day. I deleted the plugin and reinstalled the latest version. I still see the message.

**Comment by timkatzgrau** [comment]
I'm also getting this issue.

**Comment by rgomezp** [comment]
That message is being displayed by the SuperPWA plugin, not ours. Please reach out to them in order to have it removed. Cheers
