### ISSUE TITLE
OneSignal: There were no recipients

### ISSUE THREAD

**Issue by mlembach** [OneSignal/OneSignal-WordPress-Plugin#223]
**Description:**

"OneSignal: There were no recipients." after updating or publishing a new post.

**Anything else:**

After yesterday no push goes to any user.  Push interval is 1-2 each day.
About 1.8k users are subscribed.
Versions in use:
Wordpress: 5.2.5
OneSignal: 1.17.8

With debugging with Gutenberg there are three values, but the recipients is zero. Status code is 200. 
I have no idea where to look further or why it is not working anymore. 

Best regards,
Michael

**Comment by wollens42** [comment]
Same problem here.

**Comment by jkasten2** [comment]
@mlembach @wollens42 Can you update the latest 2.0.0 OneSignal plugin? We have fixed the issue with notifications not going out when updating specific post.

If you are still seeing the issue however will new posts after the update let us know

**Comment by hmemar** [comment]
Latest version 2.01. Is now worse. .. Nothing working at all.. No norifications
and no error message to say what is happening
and nothing all .
new and updated post.. 
NOT sure what you guys doing. BUT STOP IT. REvery BACK NOW.. You guuys broke everything

**Comment by hmemar** [comment]
I have reverted to to 1.17.9
and now getting the dreaded 
**OneSignal Push:There were no recipients. You likely have no subscribers.**

You guys are such good guys in the past and always were great with your updates.
so I am now going to ask you..
**DO YOU STRESS TEST YOUR PLUGINS BEFORE ISSUING OUT UPDATES**

**Comment by ellie272** [comment]
We have just started using OneSignal and the latest OS Wordpress plugin - intending to send push notifications to an IOS app. Have created a mu-plugin with php code from documentation, set 'send notifications to iOS/Android automatically' OFF, but get the 'OneSignal Push:There were no recipients'. message when publishing a post.  Works fine from OS Dashboard and if auto notifications is ON. Can't see what I'm doing wrong if anything - is it this bug?

**Comment by rgomezp** [comment]
Howdy,
This should be fixed. If you are still seeing the issue, please let us know by contacting support@onesignal.com
