### ISSUE TITLE
Widget should be hidden if browser not supported

### ISSUE THREAD

**Issue by davisshaver** [OneSignal/OneSignal-WordPress-Plugin#229]
**Description:**
Widget JS detects if browser is supported. If we are on an unsupported browser, we should try to hide the widget.

**Comment by rgomezp** [comment]
@davisshaver ,
Can you provide more details? I'm not sure what you're referring to here (i.e. admin side or public side)

**Comment by davisshaver** [comment]
Hi @rgomezp, sorry I missed this. Here is what I did. This helps ensure that the widget is not shown if the browser is not supported. https://github.com/davisshaver/OneSignal-WordPress-Plugin/commit/b38361371eef3ec9900c0fd6b8c9fb2812a63d38

**Comment by rgomezp** [comment]
No problem @davisshaver .
Sorry I haven't had a chance to get around to all your awesome contributions. Hopefully I'll have some time soon to take a look. Keep'em coming!

**Comment by davisshaver** [comment]
No problem @rgomezp. We’re running on a fork so I’m not as plugged into this repo right now but please let me know if you want any help on merging.
