### ISSUE TITLE
Send custom sounds to Mobile Devices

### ISSUE THREAD

**Issue by monza258** [OneSignal/OneSignal-WordPress-Plugin#233]
When I have customs sounds in Android and iOS Source code, is there any way to send a custom Sound to mobile users? 
An option to set that in mu-plugins or other way?

**Comment by monza258** [comment]
Hi, no reply about it? 🤷‍♂️

**Comment by rgomezp** [comment]
Howdy!
Firstly, iOS doesn't support web push yet. The only way to send a custom sound is if you're sending it to an app since the notification (Android only) is sent through the browser app in use, which controls the notification properties.  Great question! Enjoy
