### ISSUE TITLE
Where can I get unminified version of semantic-ui.js file?

### ISSUE THREAD

**Issue by kelin1003** [OneSignal/OneSignal-WordPress-Plugin#242]
**Description:**
I need an unminified version of the [semantic-ui.js](https://github.com/OneSignal/OneSignal-WordPress-Plugin/blob/master/views/javascript/semantic-ui.js) file for debugging and code review related requirements.

I already tried looking in existing issues to see if I could get some clue from there, but no luck.

**Comment by rgomezp** [comment]
Hello Kelin,
I recommend looking at the official Semantic UI site for source code. Enjoy!
