### ISSUE TITLE
AMP web push with Automattic/newspack-plugin + OneSignal-WordPress-Plugin

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-WordPress-Plugin#272]
## Scope
Creating this issue to track and discuss how to make AMP web push compatible with `Automattic/newspack-plugin` and `OneSignal-WordPress-Plugin`.

## Status
* Newspack
   - https://github.com/Automattic/newspack-plugin/pull/417
   - https://github.com/Automattic/newspack-plugin/pull/1076
* OneSignal-WordPress-Plugin
   - #276, released in [2.2.6](https://github.com/OneSignal/OneSignal-WordPress-Plugin/releases/tag/v2.2.6).

## 

## `<amp-web-push>` Tag Details
_Thanks to @westonruter for these details_
Example of the [`amp-web-push`](https://amp.dev/documentation/components/amp-web-push/) component, configured with a custom element like so:
```html
<amp-web-push
  layout="nodisplay"
  helper-iframe-url="https://example.com/helper-iframe.html"
  permission-dialog-url="https://example.com/permission-dialog.html"
  service-worker-url="https://example.com/service-worker.js"
></amp-web-push>
```

And then there are two custom elements for subscribing and unsubscribing to the notifications:

```html
<!-- A subscription widget -->
<amp-web-push-widget
  visibility="unsubscribed"
  layout="fixed"
  width="250"
  height="80"
>
  <button on="tap:amp-web-push.subscribe">Subscribe to Notifications</button>
</amp-web-push-widget>

<!-- An unsubscription widget -->
<amp-web-push-widget
  visibility="subscribed"
  layout="fixed"
  width="250"
  height="80"
>
  <button on="tap:amp-web-push.unsubscribe">
    Unsubscribe from Notifications
  </button>
</amp-web-push-widget>
```

## Integration TODO:
_Thanks again to @westonruter for these details_
So for configuration with OneSignal, I think it's mainly a matter of just supplying the relevant URLs to `<amp-web-push>`. See an [example](https://github.com/Automattic/newspack-plugin/blob/4ef2275b580e230392a77a1c2b84d3bdc58e53b8/includes/class-pwa.php#L188-L208) in the Newspack plugin's yet-unmerged PR https://github.com/Automattic/newspack-plugin/pull/417 which seeks to add AMP-compatible push notifications. The `amp-web-push` attributes could be set accordingly:

* `helper-iframe-url`: https://github.com/Automattic/newspack-plugin/blob/4ef2275b580e230392a77a1c2b84d3bdc58e53b8/includes/raw_assets/html/amp-web-push-helper-frame.html
* `permission-dialog-url`: https://github.com/Automattic/newspack-plugin/blob/4ef2275b580e230392a77a1c2b84d3bdc58e53b8/includes/raw_assets/html/amp-web-push-permission-dialog.html
* `service-worker-url`: https://github.com/Automattic/newspack-plugin/blob/4ef2275b580e230392a77a1c2b84d3bdc58e53b8/includes/raw_assets/html/amp-web-push-service-worker.js
* `service-worker-scope`: Since the OneSignal service worker no longer needs to control the page, then this could be a path to wherever the script is located (instead of `/`).

So when `amp_is_request()` returns `true`, then that component could be rendered on the page. If `false` (or the function is not defined), then the plugin could continue doing what it does at present in [`OneSignal_Public::onesignal_header()`](https://github.com/OneSignal/OneSignal-WordPress-Plugin/blob/58dc790bef0fb1b4d45469ad7436512956d05158/onesignal-public.php#L42-L343). 

See also https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/258.

**Comment by adekbadek** [comment]
Hi @jkasten2 👋
At Newspack, we're very keep to integrate OneSignal, and handling AMP in this plugin (instead of our workaround) seems like the best way forward. Is this planned to be implemented?

**Comment by rgomezp** [comment]
Howdy y'all,
It's been a while since we revisited this issue thread so I just wanted to check-in.

The plugin now automatically supports AMP ([see PR](https://github.com/OneSignal/OneSignal-WordPress-Plugin/pull/276)). From the Newspack team, have you tested the latest plugin version? I believe it should work automatically but please let us know if there is other work needed to fully support the integration.

@adekbadek

**Comment by claudiulodro** [comment]
Thanks for checking and for adding compatibility!  We have a number of people using the latest version with AMP-compatibility, and it's been working well for them so far.

If there is one feature request we can make it would be to have the AMP version respect the left/right settings from the WP Admin options screen. Currently it's [hard-coded to the right corner](https://github.com/OneSignal/OneSignal-WordPress-Plugin/blob/main/css/onsignal-amp-style.css#L17). Totally not a big deal or hurry though. Feel free to close this issue. :)

**Comment by rgomezp** [comment]
Certainly! Great to hear it's working well.

I'll create a separate issue for the placement improvement.

**Comment by gamebits** [comment]
Thanks for opening that issue regarding bell placement! https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/291
