### ISSUE TITLE
Installing service worker failed (non wp-content directory structure)

### ISSUE THREAD

**Issue by martinglover** [OneSignal/OneSignal-WordPress-Plugin#273]
**Description:**

There is an issue in the plugin requiring the directory structure to contain `wp-content`, using [Bedrock](https://github.com/roots/bedrock) doesn't follow this structure with plugins and themes under `app`, so when generating the `SERVICE_WORKER_PARAM` `scope` the path is incorrect for sdk_files is incorrect

**Steps to Reproduce Issue:**

  1. WordPress install using [bedrock](https://github.com/roots/bedrock)
  2. Install and setup plugin
  3. On loading page `Allow` notifications
  4. Console output `ServiceWorkerManager.js:363 [Service Worker Installation] Installing service worker failed SecurityError: Failed to register a ServiceWorker: The origin of the provided scope ('https://domain.comsdk_files') does not match the current origin ('https://domain.com').`

**Anything else:**

Bedrock does not use wp-content for plugins or themes and instead uses app

In the plugin file `onesignal-public.php` line 76 is returning false as a result of the plugin url being `/app/plugins/onesignal-free-web-push-notifications` not containing `wp-content`

**Comment by jkasten2** [comment]
@martinglover Thanks for report! We have confirmed the issue, have a tested fix, and it will be part of the next release.
