### ISSUE TITLE
How to set onesignal-staging env value for staging site?

### ISSUE THREAD

**Issue by kincjf** [OneSignal/OneSignal-WordPress-Plugin#314]
### How can we help?

Hello, I have installed and used the onesignal wordpress plugin.

After cloning the original site using the staging plug-in, we are developing a method of pushing to the original site when the staging site development is complete.

I want to link the onesignal-staging app project to the staging site,

  define( 'ONESIGNAL_APP_ID', 'onesignal-staging-app' );

Is there a way to specify a config value for onesignal staging in the wp-config.php file like this?
Or is there any other recommended method for handling staging onesignal env?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hello! Apologies that this question has gone stale.
If this question is still a current concern, please ping me.
