### ISSUE TITLE
Investigate supporting multi-site WordPress installations

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-WordPress-Plugin#34]

**Comment by veslorens** [comment]
Hello Jason,

May I ask if it already supports WordPress Multisite? I think I'm having an issue after network activating it, the plugin seems not showing in the network of sites.
Thank you.

**Comment by jasonpang** [comment]
Hey @veslorens,

We haven't investigated WordPress multi-site support yet. We think it's a good thing to have, but we've been busy making other features we haven't had time to look into this yet! I'm afraid our plugin doesn't support this at the moment, sorry for the inconvenience.

**Comment by jasonpang** [comment]
This is now tracked internally.
