### ISSUE TITLE
Notification sent on post update when send checkbox is unchecked

### ISSUE THREAD

**Issue by dfroberg** [OneSignal/OneSignal-WordPress-Plugin#40]
On wordpress installation the plugin send (duplicate) notifications even though the "Send notification on post update" is NOT checked.

**Comment by jasonpang** [comment]
Hi,

Sorry you're experiencing this issue. Could you please contact our support at support@onesignal.com and reference this thread? It would be really helpful if we could get a temporary (admin) login to your WordPress site, so that [we can install this plugin](https://github.com/OneSignal/WDS-Log-Post) and log what our plugin is doing when you create a post.

**Comment by dfroberg** [comment]
Hi after a bit of back and forth with Jason (Thanks!)
We found a solution that works for me.
Adding this segment to onesignal-extra.php it adds and checks for the "onesignal_sent" meta key, if present it will not send a notification for that article again.

`add_filter('onesignal_send_notification', 'onesignal_send_notification_filter', 10, 4);
function onesignal_send_notification_filter($fields, $new_status, $old_status, $post)
{
    $send_it = true;
    if ( $post ) {
        // Default is to send to everyone
        $fields['included_segments'] = ['English Users'];
        $utm_a = 'English';
        //$fields['isAndroid'] = true;
        $post_status = get_post_status ( $post->ID );
        //$fields['delayed_option'] = 'last-active';
        $fields['android_group'] = 'amn';
        $fields['android_group_message'] = ['en' => 'You have $[notif_count] new articles',
                                            'sv' => 'Du har $[notif_count] nya artiklar',
                                            'es' => 'Tienes $[notif_count] nuevos artículos',
                                            'ru' => 'У вас есть $[notif_count] новые статьи',
                                            'tr' => 'Sen $[notif_count] yeni makaleler',
                                            'ar' => 'لقد $[notif_count] مواد جديدة'];
        // Now lets figure out special cases
        $categories = get_the_category( $post->ID );
        foreach ($categories as $c ) {
            switch ($c->name) {
                case 'Español':
                    $fields['included_segments'] = ['Spanish Users','Test Users'];
                    $utm_a = 'Spanish';
                    break;
                case 'РУССКИЙ':
                    $fields['included_segments'] = ['Russian Users','Test Users'];
                    $utm_a = 'Russian';
                    break;
                case 'عربي':
                    $fields['included_segments'] = ['Arabic Users','Test Users'];
                    $utm_a = 'Arabic';
                    break;
                case 'Türkce':
                    $fields['included_segments'] = ['Turkish Users','Test Users'];
                    $utm_a = 'Turkish';
                    break;
                case 'Uncategorized':
                    $fields['included_segments'] = ['WordPress Bug Test Users'];
                    $utm_a = 'Test';
                    break;
            }

        }
        // Figure out where they came from
        $utm = '?utm_medium=ppc&utm_source=push&utm_campaign=push+notifications&utm_content='.$utm_a;
        // Make it pretty
        $title = isset( $post->post_title ) ? $post->post_title : 'New Article Posted';
        $fields['contents'] = array("en" => $title);
        $url = get_permalink($post->ID);
        $url = isset( $url ) ? esc_url( $url).''.$utm  : 'https://www.almasdarnews.com/';
        $fields['url'] = $url;
        // Add some buttons
 /*
        $fields['web_buttons'] = array(
            "id" => "read-more-button",
            "text" => "Read More",
            "icon" => "http://i.imgur.com/MIxJp1L.png",
            "url" => "$url"
        );
*/
        // Ensure only the right stuff get's posted
        if ( $post_status == 'publish' ) {
            if(stristr($url, 'autosave')) { // Just making extra sure
                // drop it
                $send_it = false;
            } else {
                // Fire away
                $sent = get_post_meta($post->ID,"onesignal_sent",true);
                if(isset($sent) && $sent == 1) {
                    $send_it = false;
                } else {
                    // add_post_meta( int $post_id, string $meta_key, mixed $meta_value, bool $unique = false )
                    add_post_meta($post->ID, 'onesignal_sent', 1, true);
                    $send_it = true;
                }
            }
        } else {
            // drop it
            $send_it = false;
        }

    } else {
        // drop it
        $send_it = false;
    }
    $fields['do_send_notification'] = $send_it;
    return $fields;
}`

**Comment by jasonpang** [comment]
I was not yet able to find out the root cause for the issue with dfroberg, and it was reproducible on his WordPress environment but not on our WordPress test environment.
