### ISSUE TITLE
Support categories for subscription and notifications

### ISSUE THREAD

**Issue by combs** [OneSignal/OneSignal-WordPress-Plugin#42]
We have a few categories on our site, which vary a lot in their post volumes and audiences. 

I'd like to be able to map WordPress post categories into OneSignal audience segments.

Users could choose "Food" or "Politics" when initially enabling notifications, and receive only notifications for posts in those categories.

**Comment by jasonpang** [comment]
This is probably one of our most popular requests, and it's so popular/useful that I don't really want to say this should be done programmatically with PHP code by extending our plugin. If we're going to do this it's going to be a sort of large undertaking that designs for the many different sites and use cases that would use this feature, and enough customization options to be useful.

**Comment by jasonpang** [comment]
See: https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/39

**Comment by combs** [comment]
Sounds good! Does that issue cover the bases--shall I close this one? (we were imagining more of an include than an exclude, but I'm sure your team will explore all of the options 😄 )

**Comment by jasonpang** [comment]
Hey @combs,

Nice to see you again! The above comment was just a mental note, but I've merged that into this one. Sorry to say we still may not get to this for a while.

**Comment by tunjiaramide** [comment]
@combs Did you ever solve this, how did you go about it, please can you share.

**Comment by combs** [comment]
No

**Comment by jasonpang** [comment]
We're tracking subscription categories in our internal issue tracker.
