### ISSUE TITLE
Allow custom notification title and content per post

### ISSUE THREAD

**Issue by ibiza69** [OneSignal/OneSignal-WordPress-Plugin#51]
Hi there!
Could it be possible to implement at wordpress plugin an option "after" the: **Send notification on post update**, that could replace the original title of the post when updated? 

Something like:

**Custom Notification Title**

---

Custom headline limit 73 characters 
When using a custom headline, this text will be used in place of the default blog post title for your posts notification.

Thanks in advance! Wonderful Job!!

**Comment by jasonpang** [comment]
Hey @ibiza69,

Sorry we missed this for so long; I think each time I was browsing the issues list, I just assumed I had opened this issue and I didn't realize it was opened by someone else!

We'll look into this.

**Comment by Glowball** [comment]
Any progress on this?  Thanks!

**Comment by jasonpang** [comment]
Hi @Glowball,

While we don't currently display a textbox to modify the post title/message, you can use some PHP to extend our WordPress plugin in a supported way.

Please see https://documentation.onesignal.com/docs/wordpress#section-customizing-wordpress-plugin-behavior and https://documentation.onesignal.com/docs/wordpress#section-onesignal_send_notification-filter.

**Comment by jasonpang** [comment]
We're tracking the general feature request to add sending options like custom titles, body, and action buttons internally in our issue tracker.

**Comment by rfischmann** [comment]
Really interested in this. Just switched from Pushwoosh to OneSignal, and their plugin had this feature built-in.

Has anyone developed a custom code for it already?

**Comment by thiagoprogramador** [comment]
Is it possible to change SITE NAME by Post Title?

**Comment by tohaitrieu** [comment]
Have any update for this feature?
