### ISSUE TITLE
Prevent web crawling of the sdk_files directory

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-WordPress-Plugin#52]
A user reported that they were seeing some search result hits on their Google Webmaster Tools console pointing to the sdk_files directory of our plugin, which (usually) returns a 403 Forbidden. This page should not be crawled.

**Comment by jasonpang** [comment]
Just an idea:

[Google's crawler bot follows the links it can find in the document](https://www.google.com/support/enterprise/static/gsa/docs/admin/74/gsa_doc_set/quick_start/quick_start_crawl.html). We have a public manifest link:

```
https://notify.tech/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/manifest.json.php?gcm_sender_id=
```

that Google's bot can definitely crawl. Our plugin by default doesn't output the path to the service worker file though, but maybe it somehow finds these files? Especially if directory listing is enabled.

**Comment by Dibbyo456** [comment]
I second this. 
I removed onesignal from one of my wp site. Few weeks later there were some errors. It shouldn't be crawled at the first place.

**Comment by Lofesa** [comment]
Perhaps robots.txt?
Disallow /sdk_files/

**Comment by Pushkraj19** [comment]
There are two solutions for that 
1. Remove the Plugin from website and use given script .
2. Copy the indexed url and go to Google search console and just remove the link from search engine.

**Comment by rgomezp** [comment]
@Pushkraj19 ,
These are both good workarounds. Thanks.

@Lofesa ,
Just for context, we heavily considered making 
the plugin prevent crawling of the directory automatically. Unfortunately, the `robots.txt` file has to be at the root-level, which the plugin doesn't have access to.

**Comment by bemyhre** [comment]
> Copy the indexed url and go to Google search console

That is not a good solution or workaround, as I believe that to be a temporary removal. 

https://support.google.com/webmasters/answer/1663419?hl=en

**Comment by raj7662** [comment]
I am facing the same issues. What should i do ?

**Comment by raj7662** [comment]
Actually I have uninstalled the wp plugin onesignal and now I have started the validation on gsc will it fix my issue.

**Comment by udiudiudiudi** [comment]
From what i know, the problem is not in google webmaster tools, its in google page insights
