### ISSUE TITLE
Prompt options custom language text not outputted for HTTPS sites

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-WordPress-Plugin#70]
This is because our plugin does not expect HTTPS sites to be able to use prompts like the sliding down prompt and other things. However, we should allow this for users who want to call `OneSignal.showHttpPrompt()` on their own (and other things).

[Conversation](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/wordpress-team/conversations/6942202219)
Related Issue: https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/69

**Comment by MrIncharge** [comment]
Looks like it's still not supported. Does anyone know if they plan on supporting this in the future?

**Comment by MrIncharge** [comment]
We have this set up for a https site running on rails. It's still not showing up.

**Comment by jasonpang** [comment]
Hey @MrIncharge,

We'll work on this soon, sorry about the inconvenience.

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-WordPress-Plugin/commit/5ca0be79d554e9d3fd05a5e69fd657a3852e047c?w=1
