### ISSUE TITLE
Implement HTTP permission request for new HTTP sites as the default

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-WordPress-Plugin#71]

**Comment by wysow** [comment]
Could this be a problem on a website using cloudflare flexible ssl certificate on front of an http website?

**Comment by jasonpang** [comment]
Hey @wysow,

No, that shouldn't be a problem.

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-WordPress-Plugin/commit/88f34cd1c14dd14c95ae2439c8826c5db3254c88

Users still won't really see the HTTP permission request unless they turn on autoRegister: true.
