### ISSUE TITLE
Add option to show a subscription confirm dialog

### ISSUE THREAD

**Issue by chown9835** [OneSignal/OneSignal-WordPress-Plugin#79]
I wish this plugin can add an option to show a confirm dialog after user click the button.

Like this screenshot:
![screenshot](http://drops.hiram.tw/V5OX+)

I concern about some people just click the button and click agree to receive notification without thinking (even not sure what's that mean), because this a new stuff of web, so I expect make sure user know what they will receive.

Thanks :)

**Comment by jasonpang** [comment]
Hey @chown9835,

When users subscribe, two things should happen to confirm their subscription:

- The subscription bell should display a message:

![image](https://cloud.githubusercontent.com/assets/1015970/22306593/9d6e820c-e2f4-11e6-900d-d7aa85cd7388.png)

- The user should get a welcome notification letting them know what to expect next time

![image](https://cloud.githubusercontent.com/assets/1015970/22306493/5547b746-e2f4-11e6-9ac5-683db9e9af2a.png)

**Comment by jasonpang** [comment]
Hey @chown9835,

When users subscribe, two things should happen to confirm their subscription:

- The subscription bell should display a message:

![image](https://cloud.githubusercontent.com/assets/1015970/22306593/9d6e820c-e2f4-11e6-900d-d7aa85cd7388.png)

- The user should get a welcome notification letting them know what to expect next time

![image](https://cloud.githubusercontent.com/assets/1015970/22306493/5547b746-e2f4-11e6-9ac5-683db9e9af2a.png)

**Comment by jasonpang** [comment]
If you're concerned the notify button may prompt too quickly, you can enable the option:

> Show the Slide Prompt before prompting users to subscribe

which will cause the slidedown prompt to appear before the browser's native permission request.
