### ISSUE TITLE
errors: Please include a case-sensitive header of Authorization: Basic  with a valid REST API key

### ISSUE THREAD

**Issue by luk911** [OneSignal/OneSignal-WordPress-Plugin#80]
Please include a case-sensitive header of Authorization: Basic  with a valid REST API key

**Comment by thesourav123** [comment]
@luk911 I am having the same issue. Did you find a solution

**Comment by jasonpang** [comment]
Please reach out to OneSignal support for these issues (support@onesignal.com, or visit onesignal.com and chat with us by clicking the red button on the lower right). Most likely the REST API Key textbox is empty or not the correct valid. Check the setup guide for how to retrieve the correct value.

**Comment by luk911** [comment]
subdomain on onesingle not set in wordpress plugin ...

**Comment by jhonatasfender** [comment]
Good morning, people can understand here;
To get the <YOUR-USER-AUTH-KEY-HERE>, we have to go to the profile account and there well contain this key, but now my error has changed: 
```
{
    "errors": [
        "Name Enter an app name"
    ]
}
```

**Comment by jasonpang** [comment]
If you're receiving this error when sending a notification when a post is published:

> Please include a case-sensitive header of Authorization: Basic with a valid REST API key

Please check your OneSignal Push configuration that the REST API Key is valid for your app ID. Log in to OneSignal, select the app matching your app ID, and [check your app's REST API Key](https://documentation.onesignal.com/docs/accounts-and-keys#section-keys-ids).

@jhonatasfender It sounds like you're trying to create an app through our API. You'll probably just need to enter an app name.

**Comment by magarrent** [comment]
In my case, the AppId or Api Key was wrong and showed this error...

Checkout this params

**Comment by hashs42** [comment]
In my case, I had to regenerate the api key -_- and then it stopped throwing the "case-sensitive header" error.
