### ISSUE TITLE
Sucuri conflict

### ISSUE THREAD

**Issue by mhlnu** [OneSignal/OneSignal-WordPress-Plugin#86]
Sucuri tends to add a "deny from all" line in the /wp-content/ .htaccess file. Now, I wouldn't delete that, but I was wondering if there's an IP address to allow for the ServiceWorker to actually work.

Trouble is, with deny from all, I get error 403. So, any ideas?

PS: Probably the same issue with Wordfence.

**Comment by gdeglin** [comment]
The serviceworker files need to be accessible from each user's browser, so there's not a single IP to whitelist.

Instead, please whitelist (allow from all) the following directory: `wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/`

**Comment by mhlnu** [comment]
Yeah, I kinda solved it, there's an option to whitelist some files in Sucuri, but it's buried somewhere in the settings and it's hard to find if you don't use it on a daily basis. I leave it here, but could you please update the FAQ/Help/Support section for other users that might have the same issue?

Anyway, besides that option, which you can find under: Hardening > Whitelist blocked PHP files, where you have to add OneSignalSDKWorker.js.php, manifest.json.php and OneSignalSDKUpdaterWorker.js.php.

Or you can just add the following lines into the .htaccess file in /wp-content/ - which, by the way, are generated by Sucuri:

`<Files OneSignalSDKWorker.js.php>
  <IfModule !mod_authz_core.c>
    Allow from all
  </IfModule>
  <IfModule mod_authz_core.c>
    Require all granted
  </IfModule>
</Files>

<Files manifest.json.php>
  <IfModule !mod_authz_core.c>
    Allow from all
  </IfModule>
  <IfModule mod_authz_core.c>
    Require all granted
  </IfModule>
</Files>

<Files OneSignalSDKUpdaterWorker.js.php>
  <IfModule !mod_authz_core.c>
    Allow from all
  </IfModule>
  <IfModule mod_authz_core.c>
    Require all granted
  </IfModule>
</Files>
`

**Comment by gdeglin** [comment]
Thanks! This is really helpful. We'll update our docs with this information.

**Comment by jasonpang** [comment]
We added [Sucuri's Whitelist File or Folder](https://kb.sucuri.net/firewall/Whitelist+and+Blacklist/whitelist-file-folder) guide to our documentation.
