### ISSUE TITLE
How do I delete OneSignal from database ?

### ISSUE THREAD

**Issue by nicolinuxfr** [OneSignal/OneSignal-WordPress-Plugin#91]
I tried OneSignal on my blog and then deleted the plugin.

Unfortunately, I still have traces of the plugin in my database. I don't really care, except all my pages try to load a resource from OneSignal and end up with a 404. How can I delete everything, and I mean really everything ?

![capture d ecran 2017-06-01 a 14 22 45](https://cloud.githubusercontent.com/assets/2078386/26679535/ce3c3600-46d5-11e7-81d5-83e79397a39c.png)

Thanks !

**Comment by jasonpang** [comment]
Hey @nicolinuxfr,

Visit chrome://serviceworker-internals, search for "voiretmanger" and click Unregister. That should do it!

**Comment by nicolinuxfr** [comment]
OK, it worked for the 404. Thanks !

**Comment by jasonpang** [comment]
@nicolinuxfr 

You're very welcome!

**Comment by howdojonesy** [comment]
Jeez, I've been looking at how to sort this for weeks!! Now sorted, thank you!
