### ISSUE TITLE
AdditionalData Wordpress Insertion

### ISSUE THREAD

**Issue by westindiantech** [OneSignal/OneSignal-WordPress-Plugin#92]
Hi, I'm trying to understand how this works and yes I've gone through the documentation.

I'm using wordpress and have successfully configured onesignal with my site, device and app. I'm also using a mu-plugin of onesignal to unset the url of the push so it opens my app and not the mobile browser.

What I want to have done now is, I would like to send from the mu-plugin additionaldata with 
Key=posts 
Value= post_id (numerical value eg 10)

How can this be done, as I'm really lost as to what to enter from the documentation.

**Comment by jasonpang** [comment]
Hi @westindiantech,

Looks like you've got the right idea. It sounds like just the code might need to be changed. Can you reach out to support@onesignal.com, link back to this question (for context) and please provide the code you have so far? Remember you need to format additionalData as a hash.

**Comment by westindiantech** [comment]
Hi, I forgot to close this. I got it solved shortly after by adding extra fields to the data array in the mu plugin.

**Comment by jasonpang** [comment]
@westindiantech Nice job! Glad you got it.
