### ISSUE TITLE
MultipleInitialization error when using translated Customize Slidedown Permission Message

### ISSUE THREAD

**Issue by ehtabar** [OneSignal/OneSignal-WordPress-Plugin#93]
Hi There,
 
When I use translated Customize Slidedown Permission Message according to OneSignal doc ( https://documentation.onesignal.com/docs/customize-permission-messages ), the message is not changed. and I get this error in the Consol of the Inspect element:
 "OneSignal: The OneSignal web SDK can only be initialized once. Extra initializations are ignored. Please remove calls initializing the SDK more than once."

The code is: 
<link rel="manifest" href="/manifest.json">
  <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
  <script>
    var OneSignal = window.OneSignal || [];
    OneSignal.push(["init", {
      appId: "***************************************",
      autoRegister: false,
   }]);
OneSignal.push(function() {
  OneSignal.showHttpPrompt();
});
// Do NOT call init() twice
OneSignal.push(["init", {
    // Your other init options here
    promptOptions: {
        /* These prompt options values configure both the HTTP prompt and the HTTP popup. */
        /* actionMessage limited to 90 characters */
        actionMessage: "We'd like to show you notifications for the latest news and updates.",
        /* acceptButtonText limited to 15 characters */
        acceptButtonText: "ALLOW",
        /* cancelButtonText limited to 15 characters */
        cancelButtonText: "NO THANKS"
    }
}]);
// Do NOT call init() twice
OneSignal.push(["init", {
    /* Your other init options here */
    welcomeNotification: {
        "title": "My Custom Title",
        "message": "Thanks for subscribing!",
        // "url": "" /* Leave commented for the notification to not open a window on Chrome and Firefox (on Safari, it opens to your webpage) */
    }
}]);
</script>

How I can use translated Customize Slidedown Permission Message without getting this error?
thank you.

**Comment by jasonpang** [comment]
Hi there,

Since you're using the WordPress plugin, please customize using our WordPress plugin instead of adding code to your site. Please remove the code from your site and fill out the red boxes highlighted in this image: https://imgur.com/a/cLrvS.

**Comment by mrtecni** [comment]
Tnx Bro
