### ISSUE TITLE
Does sub-domain causes problem while sending push notification?

### ISSUE THREAD

**Issue by vishaldodiya** [OneSignal/OneSignal-WordPress-Plugin#95]
I have used app website as https://dev.example.com which is hosted on our own server.

If I take the Header info of curl request I get this output
```
Array
(
    [url] => https://onesignal.com/api/v1/notifications
    [content_type] => 
    [http_code] => 0
    [header_size] => 0
    [request_size] => 0
    [filetime] => -1
    [ssl_verify_result] => 1
    [redirect_count] => 0
    [total_time] => 0.021277
    [namelookup_time] => 0.004423
    [connect_time] => 0.004499
    [pretransfer_time] => 0
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 127.0.0.1
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 127.0.0.1
    [local_port] => 54488
)
```

The Header size is 0. and don't get any header content.

And I get this notice.

![screenshot from 2017-08-11 18-06-14](https://user-images.githubusercontent.com/10206090/29368905-aa55b110-82be-11e7-8860-d1440c99817e.png)

**Comment by jasonpang** [comment]
Hi @vishaldodiya,

I replied to https://github.com/OneSignal/OneSignal-Website-SDK/issues/249. Please reach out to support@onesignal.com if you're still stuck on figuring this error out.
