### ISSUE TITLE
Resource Limit Exceeded OneSignal once again

### ISSUE THREAD

**Issue by idarek** [OneSignal/OneSignal-WordPress-Plugin#98]
#97 

Hi,
I need to bring it back. I have moved hosting for an icon for 3 of websites that I manage.
One website got like 1000 subscribers. I have updated post and ticked to notify people about it and website just dies because of Resources Exceeded by multiple connection, which looks directly related to OneSignal.

Is there anything else that I can try to reduce this issue when notifying through OneSignal? # #

**Comment by jasonpang** [comment]
Dup of https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/97#issuecomment-326386005
