### ISSUE TITLE
HTML comment i plugin Javascript breaks pages if automatic initialization is disabled

### ISSUE THREAD

**Issue by 16patsle** [OneSignal/OneSignal-WordPress-Plugin#99]
While tinkering with the custom initialization feature, I discovered that the plugin outputs an HTML comment in the Javascript files when this feature is enabled, which breaks the javascript.

The following code is causing the error.

```php
        if (!$use_custom_sdk_init) {
          if (has_filter('onesignal_initialize_sdk')) {
            onesignal_debug('Applying onesignal_initialize_sdk filter.');
            if (apply_filters('onesignal_initialize_sdk', $onesignal_wp_settings)) {
              // If the filter returns "$do_initialize_sdk: true", initialize the web SDK
              ?>
              OneSignal.init(window._oneSignalInitOptions);
              <?php
            } else {
              ?>
              <!-- OneSignal: onesignal_initialize_sdk filter preventing SDK initialization. -->
              <?php
            }
          } else {
            if (array_key_exists('use_slidedown_permission_message_for_https', $onesignal_wp_settings) && $onesignal_wp_settings["use_slidedown_permission_message_for_https"] == "1") {
              ?>
              oneSignal_options['autoRegister'] = false;
              OneSignal.showHttpPrompt();
              OneSignal.init(window._oneSignalInitOptions);
              <?php
            } else {
              ?>
              OneSignal.init(window._oneSignalInitOptions);
              <?php
            }
          }
        } else {
          ?>
          <!-- OneSignal: Using custom SDK initialization. -->
          <?php
        }
```

Notice the OneSignal comment at the end. This results in the following Javascript, with some comments added for clarification:

```javascript
window.OneSignal=window.OneSignal||[];
OneSignal.push(function(){
  OneSignal.SERVICE_WORKER_UPDATER_PATH="OneSignalSDKUpdaterWorker.js.php";
  OneSignal.SERVICE_WORKER_PATH="OneSignalSDKWorker.js.php";
  OneSignal.SERVICE_WORKER_PARAM={scope:'/'};
  // ... more configuration I removed to keep things short
  oneSignal_options['notifyButton']['colors']['dialog.button.background.active']='#333333';
  // The line below this is the problem:
  <!--OneSignal:Using custom SDK initialization.-->
});
```

I am using Autoptimize, which causes this code which normally is inline to be in another file. As HTML comments only work in script tags or other HTML tags, I would suggest changing the comments to use the JS syntax instead.

**Comment by jasonpang** [comment]
@16patsle,

Thanks for the detailed report. You're right this should have been a JavaScript comment. The latest `master` branch should now have this fix. Could you download a ZIP of this repo and upload it to your site to replace your current version? I'm a little hesitant to release a whole new version and trigger an update for all users just for this comment syntax change, since the issue hasn't been reported before.

**Comment by 16patsle** [comment]
Thanks for the fix. I'm using the master branch now. Am I right to understand that the fix will be included the next time an update is released?

**Comment by jasonpang** [comment]
Yes, absolutely!

**Comment by 16patsle** [comment]
Great!
